
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.stacklands
{
public sealed partial class BoosterPack : Luban.BeanBase
{
    public BoosterPack(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        NameEn = _buf.ReadString();
        NameZh = _buf.ReadString();
        DescriptionEn = _buf.ReadString();
        DescriptionZh = _buf.ReadString();
        if(_buf.ReadBool()){ PriceCardId = _buf.ReadString(); } else { PriceCardId = null; }
        PriceAmount = _buf.ReadInt();
        CardCount = _buf.ReadInt();
        AcquireMode = (stacklands.EPackAcquireMode)_buf.ReadInt();
        UnlockQuestCount = _buf.ReadInt();
        PurchaseThreshold = _buf.ReadInt();
        GrantOnce = _buf.ReadBool();
        FoilChance = _buf.ReadFloat();
        FoilSellMultiplier = _buf.ReadFloat();
        VerifyStatus = (stacklands.EVerifyStatus)_buf.ReadInt();
        SourceUrl = _buf.ReadString();
        SourceRevision = _buf.ReadString();
        SourceNote = _buf.ReadString();
    }

    public static BoosterPack DeserializeBoosterPack(ByteBuf _buf)
    {
        return new stacklands.BoosterPack(_buf);
    }

    /// <summary>
    /// 卡包 ID
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 英文名称
    /// </summary>
    public readonly string NameEn;
    /// <summary>
    /// 中文名称
    /// </summary>
    public readonly string NameZh;
    /// <summary>
    /// 英文简述
    /// </summary>
    public readonly string DescriptionEn;
    /// <summary>
    /// 中文简述
    /// </summary>
    public readonly string DescriptionZh;
    /// <summary>
    /// 货币卡牌
    /// </summary>
    public readonly string PriceCardId;
    /// <summary>
    /// 价格
    /// </summary>
    public readonly int PriceAmount;
    /// <summary>
    /// 卡牌数量
    /// </summary>
    public readonly int CardCount;
    /// <summary>
    /// 获得方式
    /// </summary>
    public readonly stacklands.EPackAcquireMode AcquireMode;
    /// <summary>
    /// 累计任务解锁数
    /// </summary>
    public readonly int UnlockQuestCount;
    /// <summary>
    /// 累计购买门槛
    /// </summary>
    public readonly int PurchaseThreshold;
    /// <summary>
    /// 是否仅发放一次
    /// </summary>
    public readonly bool GrantOnce;
    /// <summary>
    /// 闪卡概率
    /// </summary>
    public readonly float FoilChance;
    /// <summary>
    /// 闪卡售价倍率
    /// </summary>
    public readonly float FoilSellMultiplier;
    /// <summary>
    /// 核验状态
    /// </summary>
    public readonly stacklands.EVerifyStatus VerifyStatus;
    /// <summary>
    /// 来源 URL
    /// </summary>
    public readonly string SourceUrl;
    /// <summary>
    /// 来源页面修订号
    /// </summary>
    public readonly string SourceRevision;
    /// <summary>
    /// 来源说明
    /// </summary>
    public readonly string SourceNote;
   
    public const int __ID__ = 1693216539;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "nameEn:" + NameEn + ","
        + "nameZh:" + NameZh + ","
        + "descriptionEn:" + DescriptionEn + ","
        + "descriptionZh:" + DescriptionZh + ","
        + "priceCardId:" + PriceCardId + ","
        + "priceAmount:" + PriceAmount + ","
        + "cardCount:" + CardCount + ","
        + "acquireMode:" + AcquireMode + ","
        + "unlockQuestCount:" + UnlockQuestCount + ","
        + "purchaseThreshold:" + PurchaseThreshold + ","
        + "grantOnce:" + GrantOnce + ","
        + "foilChance:" + FoilChance + ","
        + "foilSellMultiplier:" + FoilSellMultiplier + ","
        + "verifyStatus:" + VerifyStatus + ","
        + "sourceUrl:" + SourceUrl + ","
        + "sourceRevision:" + SourceRevision + ","
        + "sourceNote:" + SourceNote + ","
        + "}";
    }
}
}

