
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.stacklands
{
public sealed partial class BoosterSlot : Luban.BeanBase
{
    public BoosterSlot(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        PackId = _buf.ReadString();
        PackId_Ref = null;
        SlotIndex = _buf.ReadInt();
        if(_buf.ReadBool()){ IdeaPoolId = _buf.ReadString(); } else { IdeaPoolId = null; }
        NormalPoolId = _buf.ReadString();
        NormalPoolId_Ref = null;
        if(_buf.ReadBool()){ PeacefulPoolId = _buf.ReadString(); } else { PeacefulPoolId = null; }
        if(_buf.ReadBool()){ GuaranteeCardId = _buf.ReadString(); } else { GuaranteeCardId = null; }
        if(_buf.ReadBool()){ GuaranteeCondition = _buf.ReadString(); } else { GuaranteeCondition = null; }
        VerifyStatus = (stacklands.EVerifyStatus)_buf.ReadInt();
        SourceUrl = _buf.ReadString();
        SourceRevision = _buf.ReadString();
        SourceNote = _buf.ReadString();
    }

    public static BoosterSlot DeserializeBoosterSlot(ByteBuf _buf)
    {
        return new stacklands.BoosterSlot(_buf);
    }

    /// <summary>
    /// 卡槽 ID
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 所属卡包
    /// </summary>
    public readonly string PackId;
    public stacklands.BoosterPack PackId_Ref;
    /// <summary>
    /// 卡槽序号
    /// </summary>
    public readonly int SlotIndex;
    /// <summary>
    /// 一次性点子池
    /// </summary>
    public readonly string IdeaPoolId;
    /// <summary>
    /// 常规池
    /// </summary>
    public readonly string NormalPoolId;
    public stacklands.LootPool NormalPoolId_Ref;
    /// <summary>
    /// 和平模式替换池
    /// </summary>
    public readonly string PeacefulPoolId;
    /// <summary>
    /// 保底卡牌
    /// </summary>
    public readonly string GuaranteeCardId;
    /// <summary>
    /// 保底条件
    /// </summary>
    public readonly string GuaranteeCondition;
    /// <summary>
    /// 核验状态
    /// </summary>
    public readonly stacklands.EVerifyStatus VerifyStatus;
    /// <summary>
    /// 来源 URL
    /// </summary>
    public readonly string SourceUrl;
    /// <summary>
    /// 来源页面修订号
    /// </summary>
    public readonly string SourceRevision;
    /// <summary>
    /// 来源说明
    /// </summary>
    public readonly string SourceNote;
   
    public const int __ID__ = 1693316864;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        PackId_Ref = tables.TbBoosterPack.GetOrDefault(PackId);
        NormalPoolId_Ref = tables.TbLootPool.GetOrDefault(NormalPoolId);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "packId:" + PackId + ","
        + "slotIndex:" + SlotIndex + ","
        + "ideaPoolId:" + IdeaPoolId + ","
        + "normalPoolId:" + NormalPoolId + ","
        + "peacefulPoolId:" + PeacefulPoolId + ","
        + "guaranteeCardId:" + GuaranteeCardId + ","
        + "guaranteeCondition:" + GuaranteeCondition + ","
        + "verifyStatus:" + VerifyStatus + ","
        + "sourceUrl:" + SourceUrl + ","
        + "sourceRevision:" + SourceRevision + ","
        + "sourceNote:" + SourceNote + ","
        + "}";
    }
}
}

