
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.stacklands
{
public sealed partial class CardEffect : Luban.BeanBase
{
    public CardEffect(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        SourceCardId = _buf.ReadString();
        SourceCardId_Ref = null;
        Trigger = _buf.ReadString();
        EffectType = _buf.ReadString();
        Target = _buf.ReadString();
        Chance = _buf.ReadFloat();
        DurationSeconds = _buf.ReadFloat();
        Magnitude = _buf.ReadFloat();
        MaxTriggers = _buf.ReadInt();
        OnceScope = (stacklands.EOnceScope)_buf.ReadInt();
        ConditionArg = _buf.ReadString();
        VerifyStatus = (stacklands.EVerifyStatus)_buf.ReadInt();
        SourceUrl = _buf.ReadString();
        SourceRevision = _buf.ReadString();
        SourceNote = _buf.ReadString();
    }

    public static CardEffect DeserializeCardEffect(ByteBuf _buf)
    {
        return new stacklands.CardEffect(_buf);
    }

    /// <summary>
    /// 效果 ID
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 来源卡牌
    /// </summary>
    public readonly string SourceCardId;
    public stacklands.Card SourceCardId_Ref;
    /// <summary>
    /// 触发时机
    /// </summary>
    public readonly string Trigger;
    /// <summary>
    /// 效果类型
    /// </summary>
    public readonly string EffectType;
    /// <summary>
    /// 作用目标
    /// </summary>
    public readonly string Target;
    /// <summary>
    /// 触发概率
    /// </summary>
    public readonly float Chance;
    /// <summary>
    /// 持续秒数；-1 表示到下个 Moon
    /// </summary>
    public readonly float DurationSeconds;
    /// <summary>
    /// 效果倍率/强度
    /// </summary>
    public readonly float Magnitude;
    /// <summary>
    /// 单次上限；-1 表示不限
    /// </summary>
    public readonly int MaxTriggers;
    /// <summary>
    /// 一次性范围
    /// </summary>
    public readonly stacklands.EOnceScope OnceScope;
    /// <summary>
    /// 补充条件
    /// </summary>
    public readonly string ConditionArg;
    /// <summary>
    /// 核验状态
    /// </summary>
    public readonly stacklands.EVerifyStatus VerifyStatus;
    /// <summary>
    /// 来源 URL
    /// </summary>
    public readonly string SourceUrl;
    /// <summary>
    /// 来源页面修订号
    /// </summary>
    public readonly string SourceRevision;
    /// <summary>
    /// 来源说明
    /// </summary>
    public readonly string SourceNote;
   
    public const int __ID__ = 1878627631;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        SourceCardId_Ref = tables.TbCard.GetOrDefault(SourceCardId);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "sourceCardId:" + SourceCardId + ","
        + "trigger:" + Trigger + ","
        + "effectType:" + EffectType + ","
        + "target:" + Target + ","
        + "chance:" + Chance + ","
        + "durationSeconds:" + DurationSeconds + ","
        + "magnitude:" + Magnitude + ","
        + "maxTriggers:" + MaxTriggers + ","
        + "onceScope:" + OnceScope + ","
        + "conditionArg:" + ConditionArg + ","
        + "verifyStatus:" + VerifyStatus + ","
        + "sourceUrl:" + SourceUrl + ","
        + "sourceRevision:" + SourceRevision + ","
        + "sourceNote:" + SourceNote + ","
        + "}";
    }
}
}

