
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.stacklands
{
public sealed partial class CardAmount : Luban.BeanBase
{
    public CardAmount(ByteBuf _buf) 
    {
        CardId = _buf.ReadString();
        Count = _buf.ReadInt();
    }

    public static CardAmount DeserializeCardAmount(ByteBuf _buf)
    {
        return new stacklands.CardAmount(_buf);
    }

    /// <summary>
    /// 卡牌 ID
    /// </summary>
    public readonly string CardId;
    /// <summary>
    /// 数量
    /// </summary>
    public readonly int Count;
   
    public const int __ID__ = 1770859510;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "cardId:" + CardId + ","
        + "count:" + Count + ","
        + "}";
    }
}
}

