
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.stacklands
{
public sealed partial class Card : Luban.BeanBase
{
    public Card(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        NameEn = _buf.ReadString();
        NameZh = _buf.ReadString();
        DescriptionEn = _buf.ReadString();
        DescriptionZh = _buf.ReadString();
        Category = (stacklands.ECardCategory)_buf.ReadInt();
        Color = (stacklands.ECardColor)_buf.ReadInt();
        {int n0 = _buf.ReadSize(); Tags = new System.Collections.Generic.List<stacklands.ECardTag>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { stacklands.ECardTag _e0;  _e0 = (stacklands.ECardTag)_buf.ReadInt(); Tags.Add(_e0);}}
        if(_buf.ReadBool()){ SellPrice = _buf.ReadInt(); } else { SellPrice = null; }
        if(_buf.ReadBool()){ FoodValue = _buf.ReadInt(); } else { FoodValue = null; }
        CardCapCost = _buf.ReadInt();
        if(_buf.ReadBool()){ IsSellable = _buf.ReadBool(); } else { IsSellable = null; }
        if(_buf.ReadBool()){ IsFoilEligible = _buf.ReadBool(); } else { IsFoilEligible = null; }
        if(_buf.ReadBool()){ IsUnique = _buf.ReadBool(); } else { IsUnique = null; }
        VerifyStatus = (stacklands.EVerifyStatus)_buf.ReadInt();
        SourceUrl = _buf.ReadString();
        SourceRevision = _buf.ReadString();
        SourceNote = _buf.ReadString();
    }

    public static Card DeserializeCard(ByteBuf _buf)
    {
        return new stacklands.Card(_buf);
    }

    /// <summary>
    /// Stacklands 稳定卡牌 ID
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 英文名称
    /// </summary>
    public readonly string NameEn;
    /// <summary>
    /// 中文名称
    /// </summary>
    public readonly string NameZh;
    /// <summary>
    /// 英文简述
    /// </summary>
    public readonly string DescriptionEn;
    /// <summary>
    /// 中文简述
    /// </summary>
    public readonly string DescriptionZh;
    /// <summary>
    /// 玩法分类
    /// </summary>
    public readonly stacklands.ECardCategory Category;
    /// <summary>
    /// 卡面颜色
    /// </summary>
    public readonly stacklands.ECardColor Color;
    /// <summary>
    /// 玩法标签
    /// </summary>
    public readonly System.Collections.Generic.List<stacklands.ECardTag> Tags;
    /// <summary>
    /// 基础售价
    /// </summary>
    public readonly int? SellPrice;
    /// <summary>
    /// 食物点
    /// </summary>
    public readonly int? FoodValue;
    /// <summary>
    /// 卡牌上限占用
    /// </summary>
    public readonly int CardCapCost;
    /// <summary>
    /// 是否可出售
    /// </summary>
    public readonly bool? IsSellable;
    /// <summary>
    /// 是否可成为有售价闪卡
    /// </summary>
    public readonly bool? IsFoilEligible;
    /// <summary>
    /// 是否唯一
    /// </summary>
    public readonly bool? IsUnique;
    /// <summary>
    /// 核验状态
    /// </summary>
    public readonly stacklands.EVerifyStatus VerifyStatus;
    /// <summary>
    /// 来源 URL
    /// </summary>
    public readonly string SourceUrl;
    /// <summary>
    /// 来源页面修订号
    /// </summary>
    public readonly string SourceRevision;
    /// <summary>
    /// 来源说明
    /// </summary>
    public readonly string SourceNote;
   
    public const int __ID__ = -1686182402;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "nameEn:" + NameEn + ","
        + "nameZh:" + NameZh + ","
        + "descriptionEn:" + DescriptionEn + ","
        + "descriptionZh:" + DescriptionZh + ","
        + "category:" + Category + ","
        + "color:" + Color + ","
        + "tags:" + Luban.StringUtil.CollectionToString(Tags) + ","
        + "sellPrice:" + SellPrice + ","
        + "foodValue:" + FoodValue + ","
        + "cardCapCost:" + CardCapCost + ","
        + "isSellable:" + IsSellable + ","
        + "isFoilEligible:" + IsFoilEligible + ","
        + "isUnique:" + IsUnique + ","
        + "verifyStatus:" + VerifyStatus + ","
        + "sourceUrl:" + SourceUrl + ","
        + "sourceRevision:" + SourceRevision + ","
        + "sourceNote:" + SourceNote + ","
        + "}";
    }
}
}

