
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.stacklands
{
public sealed partial class CardAction : Luban.BeanBase
{
    public CardAction(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        SourceCardId = _buf.ReadString();
        SourceCardId_Ref = null;
        ActionType = (stacklands.EActionType)_buf.ReadInt();
        WorkerRequirement = (stacklands.EWorkerRequirement)_buf.ReadInt();
        {int n0 = _buf.ReadSize(); Requirements = new System.Collections.Generic.List<stacklands.CardRequirement>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { stacklands.CardRequirement _e0;  _e0 = global::GameConfig.stacklands.CardRequirement.DeserializeCardRequirement(_buf); Requirements.Add(_e0);}}
        if(_buf.ReadBool()){ DurationSeconds = _buf.ReadFloat(); } else { DurationSeconds = null; }
        if(_buf.ReadBool()){ RepeatInterval = _buf.ReadFloat(); } else { RepeatInterval = null; }
        if(_buf.ReadBool()){ MaxUses = _buf.ReadInt(); } else { MaxUses = null; }
        if(_buf.ReadBool()){ LootPoolId = _buf.ReadString(); } else { LootPoolId = null; }
        if(_buf.ReadBool()){ MilestoneGroupId = _buf.ReadString(); } else { MilestoneGroupId = null; }
        DestroySourceOnComplete = _buf.ReadBool();
        VerifyStatus = (stacklands.EVerifyStatus)_buf.ReadInt();
        SourceUrl = _buf.ReadString();
        SourceRevision = _buf.ReadString();
        SourceNote = _buf.ReadString();
    }

    public static CardAction DeserializeCardAction(ByteBuf _buf)
    {
        return new stacklands.CardAction(_buf);
    }

    /// <summary>
    /// 动作 ID
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 动作来源卡牌
    /// </summary>
    public readonly string SourceCardId;
    public stacklands.Card SourceCardId_Ref;
    /// <summary>
    /// 动作类型
    /// </summary>
    public readonly stacklands.EActionType ActionType;
    /// <summary>
    /// 工人要求
    /// </summary>
    public readonly stacklands.EWorkerRequirement WorkerRequirement;
    /// <summary>
    /// 额外输入卡牌及消耗方式
    /// </summary>
    public readonly System.Collections.Generic.List<stacklands.CardRequirement> Requirements;
    /// <summary>
    /// 动作时长
    /// </summary>
    public readonly float? DurationSeconds;
    /// <summary>
    /// 周期产出间隔
    /// </summary>
    public readonly float? RepeatInterval;
    /// <summary>
    /// 最大使用次数
    /// </summary>
    public readonly int? MaxUses;
    /// <summary>
    /// 结果掉落池
    /// </summary>
    public readonly string LootPoolId;
    /// <summary>
    /// 里程碑组
    /// </summary>
    public readonly string MilestoneGroupId;
    /// <summary>
    /// 完成后销毁来源
    /// </summary>
    public readonly bool DestroySourceOnComplete;
    /// <summary>
    /// 核验状态
    /// </summary>
    public readonly stacklands.EVerifyStatus VerifyStatus;
    /// <summary>
    /// 来源 URL
    /// </summary>
    public readonly string SourceUrl;
    /// <summary>
    /// 来源页面修订号
    /// </summary>
    public readonly string SourceRevision;
    /// <summary>
    /// 来源说明
    /// </summary>
    public readonly string SourceNote;
   
    public const int __ID__ = 1761761748;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        SourceCardId_Ref = tables.TbCard.GetOrDefault(SourceCardId);
        foreach (var _e in Requirements) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "sourceCardId:" + SourceCardId + ","
        + "actionType:" + ActionType + ","
        + "workerRequirement:" + WorkerRequirement + ","
        + "requirements:" + Luban.StringUtil.CollectionToString(Requirements) + ","
        + "durationSeconds:" + DurationSeconds + ","
        + "repeatInterval:" + RepeatInterval + ","
        + "maxUses:" + MaxUses + ","
        + "lootPoolId:" + LootPoolId + ","
        + "milestoneGroupId:" + MilestoneGroupId + ","
        + "destroySourceOnComplete:" + DestroySourceOnComplete + ","
        + "verifyStatus:" + VerifyStatus + ","
        + "sourceUrl:" + SourceUrl + ","
        + "sourceRevision:" + SourceRevision + ","
        + "sourceNote:" + SourceNote + ","
        + "}";
    }
}
}

