
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.stacklands
{
public sealed partial class CardRequirement : Luban.BeanBase
{
    public CardRequirement(ByteBuf _buf) 
    {
        Matcher = (stacklands.ECardMatcher)_buf.ReadInt();
        if(_buf.ReadBool()){ CardId = _buf.ReadString(); } else { CardId = null; }
        if(_buf.ReadBool()){ Tag = _buf.ReadString(); } else { Tag = null; }
        Count = _buf.ReadInt();
        ConsumeMode = (stacklands.EConsumeMode)_buf.ReadInt();
    }

    public static CardRequirement DeserializeCardRequirement(ByteBuf _buf)
    {
        return new stacklands.CardRequirement(_buf);
    }

    /// <summary>
    /// 匹配方式
    /// </summary>
    public readonly stacklands.ECardMatcher Matcher;
    /// <summary>
    /// 卡牌 ID
    /// </summary>
    public readonly string CardId;
    /// <summary>
    /// 标签
    /// </summary>
    public readonly string Tag;
    /// <summary>
    /// 数量
    /// </summary>
    public readonly int Count;
    /// <summary>
    /// 消耗方式
    /// </summary>
    public readonly stacklands.EConsumeMode ConsumeMode;
   
    public const int __ID__ = -301690011;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "matcher:" + Matcher + ","
        + "cardId:" + CardId + ","
        + "tag:" + Tag + ","
        + "count:" + Count + ","
        + "consumeMode:" + ConsumeMode + ","
        + "}";
    }
}
}

