
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.stacklands
{ 
    public enum EActionType
    {
        /// <summary>
        /// HARVEST
        /// </summary>
        HARVEST = 1,
        /// <summary>
        /// PRODUCE
        /// </summary>
        PRODUCE = 2,
        /// <summary>
        /// EXPLORE
        /// </summary>
        EXPLORE = 3,
        /// <summary>
        /// OPEN
        /// </summary>
        OPEN = 4,
        /// <summary>
        /// SELL
        /// </summary>
        SELL = 5,
        /// <summary>
        /// BREED
        /// </summary>
        BREED = 6,
        /// <summary>
        /// GROW
        /// </summary>
        GROW = 7,
        /// <summary>
        /// SUMMON
        /// </summary>
        SUMMON = 8,
        /// <summary>
        /// TRADE
        /// </summary>
        TRADE = 9,
        /// <summary>
        /// SPAWN
        /// </summary>
        SPAWN = 10,
        /// <summary>
        /// DEFEAT
        /// </summary>
        DEFEAT = 11,
    }

} 

