
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.stacklands
{ 
    public enum EAttackType
    {
        /// <summary>
        /// NONE
        /// </summary>
        NONE = 1,
        /// <summary>
        /// MELEE
        /// </summary>
        MELEE = 2,
        /// <summary>
        /// RANGED
        /// </summary>
        RANGED = 3,
        /// <summary>
        /// MAGIC
        /// </summary>
        MAGIC = 4,
    }

} 

