
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.stacklands
{ 
    public enum ECardMatcher
    {
        /// <summary>
        /// EXACT
        /// </summary>
        EXACT = 1,
        /// <summary>
        /// TAG
        /// </summary>
        TAG = 2,
        /// <summary>
        /// CATEGORY
        /// </summary>
        CATEGORY = 3,
    }

} 

