
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.stacklands
{ 
    public enum ECardTag
    {
        /// <summary>
        /// ADULT
        /// </summary>
        ADULT = 1,
        /// <summary>
        /// WORKER
        /// </summary>
        WORKER = 2,
        /// <summary>
        /// HUMAN
        /// </summary>
        HUMAN = 3,
        /// <summary>
        /// ANIMAL
        /// </summary>
        ANIMAL = 4,
        /// <summary>
        /// HOSTILE
        /// </summary>
        HOSTILE = 5,
        /// <summary>
        /// BOSS
        /// </summary>
        BOSS = 6,
        /// <summary>
        /// BUILDING
        /// </summary>
        BUILDING = 7,
        /// <summary>
        /// RESOURCE_NODE
        /// </summary>
        RESOURCE_NODE = 8,
        /// <summary>
        /// FOOD
        /// </summary>
        FOOD = 9,
        /// <summary>
        /// IDEA
        /// </summary>
        IDEA = 10,
        /// <summary>
        /// RUMOR
        /// </summary>
        RUMOR = 11,
        /// <summary>
        /// EQUIPMENT
        /// </summary>
        EQUIPMENT = 12,
        /// <summary>
        /// LOCATION
        /// </summary>
        LOCATION = 13,
        /// <summary>
        /// CURRENCY
        /// </summary>
        CURRENCY = 14,
        /// <summary>
        /// FINITE
        /// </summary>
        FINITE = 15,
        /// <summary>
        /// INFINITE
        /// </summary>
        INFINITE = 16,
    }

} 

