
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.stacklands
{ 
    public enum ECardColor
    {
        /// <summary>
        /// PINK
        /// </summary>
        PINK = 1,
        /// <summary>
        /// BLACK
        /// </summary>
        BLACK = 2,
        /// <summary>
        /// RED
        /// </summary>
        RED = 3,
        /// <summary>
        /// GOLD
        /// </summary>
        GOLD = 4,
        /// <summary>
        /// YELLOW
        /// </summary>
        YELLOW = 5,
        /// <summary>
        /// SILVER
        /// </summary>
        SILVER = 6,
        /// <summary>
        /// WHITE
        /// </summary>
        WHITE = 7,
        /// <summary>
        /// GREEN
        /// </summary>
        GREEN = 8,
        /// <summary>
        /// BLUE
        /// </summary>
        BLUE = 9,
        /// <summary>
        /// ORANGE
        /// </summary>
        ORANGE = 10,
        /// <summary>
        /// LIGHT_ORANGE
        /// </summary>
        LIGHT_ORANGE = 11,
        /// <summary>
        /// BROWN
        /// </summary>
        BROWN = 12,
        /// <summary>
        /// PURPLE
        /// </summary>
        PURPLE = 13,
        /// <summary>
        /// GRAY
        /// </summary>
        GRAY = 14,
    }

} 

