
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.stacklands
{ 
    public enum ECardCategory
    {
        /// <summary>
        /// STRUCTURE
        /// </summary>
        STRUCTURE = 1,
        /// <summary>
        /// VILLAGER
        /// </summary>
        VILLAGER = 2,
        /// <summary>
        /// RESOURCE
        /// </summary>
        RESOURCE = 3,
        /// <summary>
        /// IDEA
        /// </summary>
        IDEA = 4,
        /// <summary>
        /// FOOD
        /// </summary>
        FOOD = 5,
        /// <summary>
        /// MOB
        /// </summary>
        MOB = 6,
        /// <summary>
        /// LOCATION
        /// </summary>
        LOCATION = 7,
        /// <summary>
        /// RUMOR
        /// </summary>
        RUMOR = 8,
        /// <summary>
        /// EQUIPMENT
        /// </summary>
        EQUIPMENT = 9,
    }

} 

