
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.stacklands
{ 
    public enum ECompareOp
    {
        /// <summary>
        /// AT_LEAST
        /// </summary>
        AT_LEAST = 1,
        /// <summary>
        /// EQUAL
        /// </summary>
        EQUAL = 2,
    }

} 

