
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.stacklands
{ 
    public enum EConditionType
    {
        /// <summary>
        /// NONE
        /// </summary>
        NONE = 1,
        /// <summary>
        /// PEACEFUL_MODE
        /// </summary>
        PEACEFUL_MODE = 2,
        /// <summary>
        /// OWNED_COUNT_LESS_THAN
        /// </summary>
        OWNED_COUNT_LESS_THAN = 3,
        /// <summary>
        /// IDEA_UNDISCOVERED
        /// </summary>
        IDEA_UNDISCOVERED = 4,
        /// <summary>
        /// ALL_IDEAS_DISCOVERED
        /// </summary>
        ALL_IDEAS_DISCOVERED = 5,
        /// <summary>
        /// PACK_PURCHASE_COUNT
        /// </summary>
        PACK_PURCHASE_COUNT = 6,
        /// <summary>
        /// MOON_AT_LEAST
        /// </summary>
        MOON_AT_LEAST = 7,
    }

} 

