
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.stacklands
{ 
    public enum EConditionMode
    {
        /// <summary>
        /// ALL
        /// </summary>
        ALL = 1,
        /// <summary>
        /// ANY
        /// </summary>
        ANY = 2,
    }

} 

