
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.stacklands
{ 
    public enum EConsumeMode
    {
        /// <summary>
        /// CONSUME
        /// </summary>
        CONSUME = 1,
        /// <summary>
        /// RETAIN
        /// </summary>
        RETAIN = 2,
        /// <summary>
        /// TRANSFORM
        /// </summary>
        TRANSFORM = 3,
        /// <summary>
        /// EQUIP
        /// </summary>
        EQUIP = 4,
    }

} 

