
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.stacklands
{ 
    public enum EEquipmentSlot
    {
        /// <summary>
        /// NONE
        /// </summary>
        NONE = 1,
        /// <summary>
        /// HAND
        /// </summary>
        HAND = 2,
        /// <summary>
        /// BODY
        /// </summary>
        BODY = 3,
        /// <summary>
        /// HEAD
        /// </summary>
        HEAD = 4,
    }

} 

