
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.stacklands
{ 
    public enum EOnceScope
    {
        /// <summary>
        /// NONE
        /// </summary>
        NONE = 1,
        /// <summary>
        /// RUN
        /// </summary>
        RUN = 2,
        /// <summary>
        /// PROFILE
        /// </summary>
        PROFILE = 3,
    }

} 

