
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.stacklands
{ 
    public enum EPackAcquireMode
    {
        /// <summary>
        /// PURCHASE
        /// </summary>
        PURCHASE = 1,
        /// <summary>
        /// AUTO_START
        /// </summary>
        AUTO_START = 2,
        /// <summary>
        /// MILESTONE
        /// </summary>
        MILESTONE = 3,
    }

} 

