
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.stacklands
{ 
    public enum EQuestSeries
    {
        /// <summary>
        /// WELCOME
        /// </summary>
        WELCOME = 1,
        /// <summary>
        /// GRAND_SCHEME
        /// </summary>
        GRAND_SCHEME = 2,
        /// <summary>
        /// POWER_SKILL
        /// </summary>
        POWER_SKILL = 3,
        /// <summary>
        /// POTLUCK
        /// </summary>
        POTLUCK = 4,
        /// <summary>
        /// DISCOVERY
        /// </summary>
        DISCOVERY = 5,
        /// <summary>
        /// WAYS_MEANS
        /// </summary>
        WAYS_MEANS = 6,
        /// <summary>
        /// CONSTRUCTION
        /// </summary>
        CONSTRUCTION = 7,
        /// <summary>
        /// LONGEVITY
        /// </summary>
        LONGEVITY = 8,
    }

} 

