
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.stacklands
{ 
    public enum EQuestMetric
    {
        /// <summary>
        /// EVENT_COUNT
        /// </summary>
        EVENT_COUNT = 1,
        /// <summary>
        /// CARD_COUNT
        /// </summary>
        CARD_COUNT = 2,
        /// <summary>
        /// TOTAL_FOOD
        /// </summary>
        TOTAL_FOOD = 3,
        /// <summary>
        /// COIN_COUNT
        /// </summary>
        COIN_COUNT = 4,
        /// <summary>
        /// IDEA_DISCOVERED_COUNT
        /// </summary>
        IDEA_DISCOVERED_COUNT = 5,
        /// <summary>
        /// REACH_MOON
        /// </summary>
        REACH_MOON = 6,
        /// <summary>
        /// PACK_UNLOCKED
        /// </summary>
        PACK_UNLOCKED = 7,
        /// <summary>
        /// PACK_OPENED
        /// </summary>
        PACK_OPENED = 8,
        /// <summary>
        /// PACK_PURCHASED
        /// </summary>
        PACK_PURCHASED = 9,
        /// <summary>
        /// CARD_OBTAINED
        /// </summary>
        CARD_OBTAINED = 10,
        /// <summary>
        /// CARD_CREATED
        /// </summary>
        CARD_CREATED = 11,
        /// <summary>
        /// CARD_KILLED
        /// </summary>
        CARD_KILLED = 12,
        /// <summary>
        /// LOCATION_EXPLORED
        /// </summary>
        LOCATION_EXPLORED = 13,
        /// <summary>
        /// STATE_CHECK
        /// </summary>
        STATE_CHECK = 14,
    }

} 

