
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.stacklands
{
public sealed partial class Equipment : Luban.BeanBase
{
    public Equipment(ByteBuf _buf) 
    {
        CardId = _buf.ReadString();
        CardId_Ref = null;
        Slot = (stacklands.EEquipmentSlot)_buf.ReadInt();
        AttackType = (stacklands.EAttackType)_buf.ReadInt();
        ProfessionCardId = _buf.ReadString();
        AttackSpeedDelta = _buf.ReadInt();
        HitDelta = _buf.ReadInt();
        DamageDelta = _buf.ReadInt();
        DefenseDelta = _buf.ReadInt();
        ExploreSpeedMultiplier = _buf.ReadFloat();
        WorkSpeedMultiplier = _buf.ReadFloat();
        VerifyStatus = (stacklands.EVerifyStatus)_buf.ReadInt();
        SourceUrl = _buf.ReadString();
        SourceRevision = _buf.ReadString();
        SourceNote = _buf.ReadString();
    }

    public static Equipment DeserializeEquipment(ByteBuf _buf)
    {
        return new stacklands.Equipment(_buf);
    }

    /// <summary>
    /// 装备卡牌
    /// </summary>
    public readonly string CardId;
    public stacklands.Card CardId_Ref;
    /// <summary>
    /// 装备槽
    /// </summary>
    public readonly stacklands.EEquipmentSlot Slot;
    /// <summary>
    /// 攻击类型
    /// </summary>
    public readonly stacklands.EAttackType AttackType;
    /// <summary>
    /// 装备后职业卡牌
    /// </summary>
    public readonly string ProfessionCardId;
    /// <summary>
    /// 攻速档位修正
    /// </summary>
    public readonly int AttackSpeedDelta;
    /// <summary>
    /// 命中档位修正
    /// </summary>
    public readonly int HitDelta;
    /// <summary>
    /// 伤害档位修正
    /// </summary>
    public readonly int DamageDelta;
    /// <summary>
    /// 防御档位修正
    /// </summary>
    public readonly int DefenseDelta;
    /// <summary>
    /// 探索速度倍率
    /// </summary>
    public readonly float ExploreSpeedMultiplier;
    /// <summary>
    /// 工作速度倍率
    /// </summary>
    public readonly float WorkSpeedMultiplier;
    /// <summary>
    /// 核验状态
    /// </summary>
    public readonly stacklands.EVerifyStatus VerifyStatus;
    /// <summary>
    /// 来源 URL
    /// </summary>
    public readonly string SourceUrl;
    /// <summary>
    /// 来源页面修订号
    /// </summary>
    public readonly string SourceRevision;
    /// <summary>
    /// 来源说明
    /// </summary>
    public readonly string SourceNote;
   
    public const int __ID__ = -1364517024;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        CardId_Ref = tables.TbCard.GetOrDefault(CardId);
    }

    public override string ToString()
    {
        return "{ "
        + "cardId:" + CardId + ","
        + "slot:" + Slot + ","
        + "attackType:" + AttackType + ","
        + "professionCardId:" + ProfessionCardId + ","
        + "attackSpeedDelta:" + AttackSpeedDelta + ","
        + "hitDelta:" + HitDelta + ","
        + "damageDelta:" + DamageDelta + ","
        + "defenseDelta:" + DefenseDelta + ","
        + "exploreSpeedMultiplier:" + ExploreSpeedMultiplier + ","
        + "workSpeedMultiplier:" + WorkSpeedMultiplier + ","
        + "verifyStatus:" + VerifyStatus + ","
        + "sourceUrl:" + SourceUrl + ","
        + "sourceRevision:" + SourceRevision + ","
        + "sourceNote:" + SourceNote + ","
        + "}";
    }
}
}

