
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.stacklands
{ 
    public enum ERecipeGroup
    {
        /// <summary>
        /// BUILDING
        /// </summary>
        BUILDING = 1,
        /// <summary>
        /// RESOURCE
        /// </summary>
        RESOURCE = 2,
        /// <summary>
        /// FOOD
        /// </summary>
        FOOD = 3,
        /// <summary>
        /// POPULATION
        /// </summary>
        POPULATION = 4,
        /// <summary>
        /// EQUIPMENT
        /// </summary>
        EQUIPMENT = 5,
        /// <summary>
        /// SPECIAL
        /// </summary>
        SPECIAL = 6,
    }

} 

