
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.stacklands
{ 
    public enum EStructureType
    {
        /// <summary>
        /// HARVESTABLE
        /// </summary>
        HARVESTABLE = 1,
        /// <summary>
        /// PRODUCTION
        /// </summary>
        PRODUCTION = 2,
        /// <summary>
        /// STORAGE
        /// </summary>
        STORAGE = 3,
        /// <summary>
        /// MARKET
        /// </summary>
        MARKET = 4,
        /// <summary>
        /// HOUSING
        /// </summary>
        HOUSING = 5,
        /// <summary>
        /// PORTAL
        /// </summary>
        PORTAL = 6,
        /// <summary>
        /// SPECIAL
        /// </summary>
        SPECIAL = 7,
    }

} 

