
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.stacklands
{ 
    public enum EUnitFaction
    {
        /// <summary>
        /// FRIENDLY
        /// </summary>
        FRIENDLY = 1,
        /// <summary>
        /// HOSTILE
        /// </summary>
        HOSTILE = 2,
        /// <summary>
        /// BOSS
        /// </summary>
        BOSS = 3,
    }

} 

