
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.stacklands
{ 
    public enum EVerifyStatus
    {
        /// <summary>
        /// VERIFIED
        /// </summary>
        VERIFIED = 1,
        /// <summary>
        /// PARTIAL
        /// </summary>
        PARTIAL = 2,
        /// <summary>
        /// UNVERIFIED
        /// </summary>
        UNVERIFIED = 3,
        /// <summary>
        /// CONFLICT
        /// </summary>
        CONFLICT = 4,
    }

} 

