
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.stacklands
{ 
    public enum EWorkerRequirement
    {
        /// <summary>
        /// NONE
        /// </summary>
        NONE = 1,
        /// <summary>
        /// WORKER
        /// </summary>
        WORKER = 2,
        /// <summary>
        /// ADULT
        /// </summary>
        ADULT = 3,
        /// <summary>
        /// HUMAN
        /// </summary>
        HUMAN = 4,
        /// <summary>
        /// VILLAGER
        /// </summary>
        VILLAGER = 5,
        /// <summary>
        /// EXPLORER
        /// </summary>
        EXPLORER = 6,
    }

} 

