
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.stacklands
{
public sealed partial class LootEntry : Luban.BeanBase
{
    public LootEntry(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        PoolId = _buf.ReadString();
        PoolId_Ref = null;
        ResultCardId = _buf.ReadString();
        ResultCardId_Ref = null;
        MinCount = _buf.ReadInt();
        MaxCount = _buf.ReadInt();
        if(_buf.ReadBool()){ Weight = _buf.ReadFloat(); } else { Weight = null; }
        ConditionType = (stacklands.EConditionType)_buf.ReadInt();
        if(_buf.ReadBool()){ ConditionArg = _buf.ReadString(); } else { ConditionArg = null; }
        OnceScope = (stacklands.EOnceScope)_buf.ReadInt();
        Priority = _buf.ReadInt();
        VerifyStatus = (stacklands.EVerifyStatus)_buf.ReadInt();
        SourceUrl = _buf.ReadString();
        SourceRevision = _buf.ReadString();
        SourceNote = _buf.ReadString();
    }

    public static LootEntry DeserializeLootEntry(ByteBuf _buf)
    {
        return new stacklands.LootEntry(_buf);
    }

    /// <summary>
    /// 掉落项 ID
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 掉落池
    /// </summary>
    public readonly string PoolId;
    public stacklands.LootPool PoolId_Ref;
    /// <summary>
    /// 结果卡牌
    /// </summary>
    public readonly string ResultCardId;
    public stacklands.Card ResultCardId_Ref;
    /// <summary>
    /// 最少数量
    /// </summary>
    public readonly int MinCount;
    /// <summary>
    /// 最多数量
    /// </summary>
    public readonly int MaxCount;
    /// <summary>
    /// 相对权重；未知时为 null
    /// </summary>
    public readonly float? Weight;
    /// <summary>
    /// 条件类型
    /// </summary>
    public readonly stacklands.EConditionType ConditionType;
    /// <summary>
    /// 条件参数
    /// </summary>
    public readonly string ConditionArg;
    /// <summary>
    /// 一次性范围
    /// </summary>
    public readonly stacklands.EOnceScope OnceScope;
    /// <summary>
    /// 优先级
    /// </summary>
    public readonly int Priority;
    /// <summary>
    /// 核验状态
    /// </summary>
    public readonly stacklands.EVerifyStatus VerifyStatus;
    /// <summary>
    /// 来源 URL
    /// </summary>
    public readonly string SourceUrl;
    /// <summary>
    /// 来源页面修订号
    /// </summary>
    public readonly string SourceRevision;
    /// <summary>
    /// 来源说明
    /// </summary>
    public readonly string SourceNote;
   
    public const int __ID__ = -1077250948;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        PoolId_Ref = tables.TbLootPool.GetOrDefault(PoolId);
        ResultCardId_Ref = tables.TbCard.GetOrDefault(ResultCardId);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "poolId:" + PoolId + ","
        + "resultCardId:" + ResultCardId + ","
        + "minCount:" + MinCount + ","
        + "maxCount:" + MaxCount + ","
        + "weight:" + Weight + ","
        + "conditionType:" + ConditionType + ","
        + "conditionArg:" + ConditionArg + ","
        + "onceScope:" + OnceScope + ","
        + "priority:" + Priority + ","
        + "verifyStatus:" + VerifyStatus + ","
        + "sourceUrl:" + SourceUrl + ","
        + "sourceRevision:" + SourceRevision + ","
        + "sourceNote:" + SourceNote + ","
        + "}";
    }
}
}

