
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.stacklands
{
public sealed partial class LootPool : Luban.BeanBase
{
    public LootPool(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        DrawMin = _buf.ReadInt();
        DrawMax = _buf.ReadInt();
        NormalizeWeights = _buf.ReadBool();
        WithoutReplacement = _buf.ReadBool();
        if(_buf.ReadBool()){ FallbackPoolId = _buf.ReadString(); } else { FallbackPoolId = null; }
        VerifyStatus = (stacklands.EVerifyStatus)_buf.ReadInt();
        SourceUrl = _buf.ReadString();
        SourceRevision = _buf.ReadString();
        SourceNote = _buf.ReadString();
    }

    public static LootPool DeserializeLootPool(ByteBuf _buf)
    {
        return new stacklands.LootPool(_buf);
    }

    /// <summary>
    /// 掉落池 ID
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 最少抽取数
    /// </summary>
    public readonly int DrawMin;
    /// <summary>
    /// 最多抽取数
    /// </summary>
    public readonly int DrawMax;
    /// <summary>
    /// 是否归一化权重
    /// </summary>
    public readonly bool NormalizeWeights;
    /// <summary>
    /// 是否不放回
    /// </summary>
    public readonly bool WithoutReplacement;
    /// <summary>
    /// 后备池
    /// </summary>
    public readonly string FallbackPoolId;
    /// <summary>
    /// 核验状态
    /// </summary>
    public readonly stacklands.EVerifyStatus VerifyStatus;
    /// <summary>
    /// 来源 URL
    /// </summary>
    public readonly string SourceUrl;
    /// <summary>
    /// 来源页面修订号
    /// </summary>
    public readonly string SourceRevision;
    /// <summary>
    /// 来源说明
    /// </summary>
    public readonly string SourceNote;
   
    public const int __ID__ = -588610862;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "drawMin:" + DrawMin + ","
        + "drawMax:" + DrawMax + ","
        + "normalizeWeights:" + NormalizeWeights + ","
        + "withoutReplacement:" + WithoutReplacement + ","
        + "fallbackPoolId:" + FallbackPoolId + ","
        + "verifyStatus:" + VerifyStatus + ","
        + "sourceUrl:" + SourceUrl + ","
        + "sourceRevision:" + SourceRevision + ","
        + "sourceNote:" + SourceNote + ","
        + "}";
    }
}
}

