
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.stacklands
{
public sealed partial class Milestone : Luban.BeanBase
{
    public Milestone(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        GroupId = _buf.ReadString();
        TriggerCount = _buf.ReadInt();
        if(_buf.ReadBool()){ OutputCardId = _buf.ReadString(); } else { OutputCardId = null; }
        OutputCount = _buf.ReadInt();
        ReplaceRandomResult = _buf.ReadBool();
        DestroySource = _buf.ReadBool();
        OnceScope = (stacklands.EOnceScope)_buf.ReadInt();
        VerifyStatus = (stacklands.EVerifyStatus)_buf.ReadInt();
        SourceUrl = _buf.ReadString();
        SourceRevision = _buf.ReadString();
        SourceNote = _buf.ReadString();
    }

    public static Milestone DeserializeMilestone(ByteBuf _buf)
    {
        return new stacklands.Milestone(_buf);
    }

    /// <summary>
    /// 里程碑 ID
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 里程碑组
    /// </summary>
    public readonly string GroupId;
    /// <summary>
    /// 触发次数
    /// </summary>
    public readonly int TriggerCount;
    /// <summary>
    /// 固定输出卡牌
    /// </summary>
    public readonly string OutputCardId;
    /// <summary>
    /// 输出数量
    /// </summary>
    public readonly int OutputCount;
    /// <summary>
    /// 是否替换随机结果
    /// </summary>
    public readonly bool ReplaceRandomResult;
    /// <summary>
    /// 是否销毁来源
    /// </summary>
    public readonly bool DestroySource;
    /// <summary>
    /// 一次性范围
    /// </summary>
    public readonly stacklands.EOnceScope OnceScope;
    /// <summary>
    /// 核验状态
    /// </summary>
    public readonly stacklands.EVerifyStatus VerifyStatus;
    /// <summary>
    /// 来源 URL
    /// </summary>
    public readonly string SourceUrl;
    /// <summary>
    /// 来源页面修订号
    /// </summary>
    public readonly string SourceRevision;
    /// <summary>
    /// 来源说明
    /// </summary>
    public readonly string SourceNote;
   
    public const int __ID__ = 789009218;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "groupId:" + GroupId + ","
        + "triggerCount:" + TriggerCount + ","
        + "outputCardId:" + OutputCardId + ","
        + "outputCount:" + OutputCount + ","
        + "replaceRandomResult:" + ReplaceRandomResult + ","
        + "destroySource:" + DestroySource + ","
        + "onceScope:" + OnceScope + ","
        + "verifyStatus:" + VerifyStatus + ","
        + "sourceUrl:" + SourceUrl + ","
        + "sourceRevision:" + SourceRevision + ","
        + "sourceNote:" + SourceNote + ","
        + "}";
    }
}
}

