
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.stacklands
{
public sealed partial class Quest : Luban.BeanBase
{
    public Quest(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        Series = (stacklands.EQuestSeries)_buf.ReadInt();
        Order = _buf.ReadInt();
        NameEn = _buf.ReadString();
        NameZh = _buf.ReadString();
        DescriptionEn = _buf.ReadString();
        DescriptionZh = _buf.ReadString();
        {int n0 = _buf.ReadSize(); Conditions = new System.Collections.Generic.List<stacklands.QuestCondition>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { stacklands.QuestCondition _e0;  _e0 = global::GameConfig.stacklands.QuestCondition.DeserializeQuestCondition(_buf); Conditions.Add(_e0);}}
        ConditionMode = (stacklands.EConditionMode)_buf.ReadInt();
        Persistence = (stacklands.EQuestPersistence)_buf.ReadInt();
        IsMain = _buf.ReadBool();
        VerifyStatus = (stacklands.EVerifyStatus)_buf.ReadInt();
        SourceUrl = _buf.ReadString();
        SourceRevision = _buf.ReadString();
        SourceNote = _buf.ReadString();
    }

    public static Quest DeserializeQuest(ByteBuf _buf)
    {
        return new stacklands.Quest(_buf);
    }

    /// <summary>
    /// 任务 ID
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 任务系列
    /// </summary>
    public readonly stacklands.EQuestSeries Series;
    /// <summary>
    /// 系列内序号
    /// </summary>
    public readonly int Order;
    /// <summary>
    /// 英文名称
    /// </summary>
    public readonly string NameEn;
    /// <summary>
    /// 中文名称
    /// </summary>
    public readonly string NameZh;
    /// <summary>
    /// 英文简述
    /// </summary>
    public readonly string DescriptionEn;
    /// <summary>
    /// 中文条件说明
    /// </summary>
    public readonly string DescriptionZh;
    /// <summary>
    /// 完成条件
    /// </summary>
    public readonly System.Collections.Generic.List<stacklands.QuestCondition> Conditions;
    /// <summary>
    /// 条件组合
    /// </summary>
    public readonly stacklands.EConditionMode ConditionMode;
    /// <summary>
    /// 完成记录范围
    /// </summary>
    public readonly stacklands.EQuestPersistence Persistence;
    /// <summary>
    /// 是否主线
    /// </summary>
    public readonly bool IsMain;
    /// <summary>
    /// 核验状态
    /// </summary>
    public readonly stacklands.EVerifyStatus VerifyStatus;
    /// <summary>
    /// 来源 URL
    /// </summary>
    public readonly string SourceUrl;
    /// <summary>
    /// 来源页面修订号
    /// </summary>
    public readonly string SourceRevision;
    /// <summary>
    /// 来源说明
    /// </summary>
    public readonly string SourceNote;
   
    public const int __ID__ = -718533708;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in Conditions) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "series:" + Series + ","
        + "order:" + Order + ","
        + "nameEn:" + NameEn + ","
        + "nameZh:" + NameZh + ","
        + "descriptionEn:" + DescriptionEn + ","
        + "descriptionZh:" + DescriptionZh + ","
        + "conditions:" + Luban.StringUtil.CollectionToString(Conditions) + ","
        + "conditionMode:" + ConditionMode + ","
        + "persistence:" + Persistence + ","
        + "isMain:" + IsMain + ","
        + "verifyStatus:" + VerifyStatus + ","
        + "sourceUrl:" + SourceUrl + ","
        + "sourceRevision:" + SourceRevision + ","
        + "sourceNote:" + SourceNote + ","
        + "}";
    }
}
}

