
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.stacklands
{
public sealed partial class QuestCondition : Luban.BeanBase
{
    public QuestCondition(ByteBuf _buf) 
    {
        Metric = (stacklands.EQuestMetric)_buf.ReadInt();
        TargetId = _buf.ReadString();
        if(_buf.ReadBool()){ TargetCardId = _buf.ReadString(); } else { TargetCardId = null; }
        if(_buf.ReadBool()){ TargetPackId = _buf.ReadString(); } else { TargetPackId = null; }
        if(_buf.ReadBool()){ TargetRecipeId = _buf.ReadString(); } else { TargetRecipeId = null; }
        Compare = (stacklands.ECompareOp)_buf.ReadInt();
        Threshold = _buf.ReadInt();
        Scope = (stacklands.EQuestPersistence)_buf.ReadInt();
    }

    public static QuestCondition DeserializeQuestCondition(ByteBuf _buf)
    {
        return new stacklands.QuestCondition(_buf);
    }

    /// <summary>
    /// 指标
    /// </summary>
    public readonly stacklands.EQuestMetric Metric;
    /// <summary>
    /// 通用目标 ID
    /// </summary>
    public readonly string TargetId;
    /// <summary>
    /// 目标卡牌
    /// </summary>
    public readonly string TargetCardId;
    /// <summary>
    /// 目标卡包
    /// </summary>
    public readonly string TargetPackId;
    /// <summary>
    /// 目标配方
    /// </summary>
    public readonly string TargetRecipeId;
    /// <summary>
    /// 比较符
    /// </summary>
    public readonly stacklands.ECompareOp Compare;
    /// <summary>
    /// 阈值
    /// </summary>
    public readonly int Threshold;
    /// <summary>
    /// 条件统计范围
    /// </summary>
    public readonly stacklands.EQuestPersistence Scope;
   
    public const int __ID__ = 1810852807;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "metric:" + Metric + ","
        + "targetId:" + TargetId + ","
        + "targetCardId:" + TargetCardId + ","
        + "targetPackId:" + TargetPackId + ","
        + "targetRecipeId:" + TargetRecipeId + ","
        + "compare:" + Compare + ","
        + "threshold:" + Threshold + ","
        + "scope:" + Scope + ","
        + "}";
    }
}
}

