
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.stacklands
{
public sealed partial class Recipe : Luban.BeanBase
{
    public Recipe(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        BlueprintId = _buf.ReadString();
        if(_buf.ReadBool()){ IdeaCardId = _buf.ReadString(); } else { IdeaCardId = null; }
        Group = (stacklands.ERecipeGroup)_buf.ReadInt();
        Priority = _buf.ReadInt();
        if(_buf.ReadBool()){ DurationSeconds = _buf.ReadFloat(); } else { DurationSeconds = null; }
        {int n0 = _buf.ReadSize(); Requirements = new System.Collections.Generic.List<stacklands.CardRequirement>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { stacklands.CardRequirement _e0;  _e0 = global::GameConfig.stacklands.CardRequirement.DeserializeCardRequirement(_buf); Requirements.Add(_e0);}}
        {int n0 = _buf.ReadSize(); Results = new System.Collections.Generic.List<stacklands.CardAmount>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { stacklands.CardAmount _e0;  _e0 = global::GameConfig.stacklands.CardAmount.DeserializeCardAmount(_buf); Results.Add(_e0);}}
        AllowExtraCards = _buf.ReadBool();
        VerifyStatus = (stacklands.EVerifyStatus)_buf.ReadInt();
        SourceUrl = _buf.ReadString();
        SourceRevision = _buf.ReadString();
        SourceNote = _buf.ReadString();
    }

    public static Recipe DeserializeRecipe(ByteBuf _buf)
    {
        return new stacklands.Recipe(_buf);
    }

    /// <summary>
    /// 配方变体 ID
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 蓝图分组 ID
    /// </summary>
    public readonly string BlueprintId;
    /// <summary>
    /// 对应点子卡
    /// </summary>
    public readonly string IdeaCardId;
    /// <summary>
    /// 配方组
    /// </summary>
    public readonly stacklands.ERecipeGroup Group;
    /// <summary>
    /// 匹配优先级
    /// </summary>
    public readonly int Priority;
    /// <summary>
    /// 耗时秒
    /// </summary>
    public readonly float? DurationSeconds;
    /// <summary>
    /// 无序输入卡牌及消耗方式
    /// </summary>
    public readonly System.Collections.Generic.List<stacklands.CardRequirement> Requirements;
    /// <summary>
    /// 结果卡牌
    /// </summary>
    public readonly System.Collections.Generic.List<stacklands.CardAmount> Results;
    /// <summary>
    /// 是否允许额外卡牌
    /// </summary>
    public readonly bool AllowExtraCards;
    /// <summary>
    /// 核验状态
    /// </summary>
    public readonly stacklands.EVerifyStatus VerifyStatus;
    /// <summary>
    /// 来源 URL
    /// </summary>
    public readonly string SourceUrl;
    /// <summary>
    /// 来源页面修订号
    /// </summary>
    public readonly string SourceRevision;
    /// <summary>
    /// 来源说明
    /// </summary>
    public readonly string SourceNote;
   
    public const int __ID__ = -785924868;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in Requirements) { _e?.ResolveRef(tables); }
        foreach (var _e in Results) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "blueprintId:" + BlueprintId + ","
        + "ideaCardId:" + IdeaCardId + ","
        + "group:" + Group + ","
        + "priority:" + Priority + ","
        + "durationSeconds:" + DurationSeconds + ","
        + "requirements:" + Luban.StringUtil.CollectionToString(Requirements) + ","
        + "results:" + Luban.StringUtil.CollectionToString(Results) + ","
        + "allowExtraCards:" + AllowExtraCards + ","
        + "verifyStatus:" + VerifyStatus + ","
        + "sourceUrl:" + SourceUrl + ","
        + "sourceRevision:" + SourceRevision + ","
        + "sourceNote:" + SourceNote + ","
        + "}";
    }
}
}

