
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.stacklands
{
public sealed partial class Structure : Luban.BeanBase
{
    public Structure(ByteBuf _buf) 
    {
        CardId = _buf.ReadString();
        CardId_Ref = null;
        StructureType = (stacklands.EStructureType)_buf.ReadInt();
        if(_buf.ReadBool()){ Capacity = _buf.ReadInt(); } else { Capacity = null; }
        CardCapDelta = _buf.ReadInt();
        IsInfinite = _buf.ReadBool();
        if(_buf.ReadBool()){ SellDuration = _buf.ReadFloat(); } else { SellDuration = null; }
        if(_buf.ReadBool()){ SellMultiplier = _buf.ReadFloat(); } else { SellMultiplier = null; }
        VerifyStatus = (stacklands.EVerifyStatus)_buf.ReadInt();
        SourceUrl = _buf.ReadString();
        SourceRevision = _buf.ReadString();
        SourceNote = _buf.ReadString();
    }

    public static Structure DeserializeStructure(ByteBuf _buf)
    {
        return new stacklands.Structure(_buf);
    }

    /// <summary>
    /// 结构卡牌
    /// </summary>
    public readonly string CardId;
    public stacklands.Card CardId_Ref;
    /// <summary>
    /// 结构类型
    /// </summary>
    public readonly stacklands.EStructureType StructureType;
    /// <summary>
    /// 容纳数量
    /// </summary>
    public readonly int? Capacity;
    /// <summary>
    /// 卡牌上限修正
    /// </summary>
    public readonly int CardCapDelta;
    /// <summary>
    /// 是否无限产出
    /// </summary>
    public readonly bool IsInfinite;
    /// <summary>
    /// 市场出售时长
    /// </summary>
    public readonly float? SellDuration;
    /// <summary>
    /// 市场售价倍率
    /// </summary>
    public readonly float? SellMultiplier;
    /// <summary>
    /// 核验状态
    /// </summary>
    public readonly stacklands.EVerifyStatus VerifyStatus;
    /// <summary>
    /// 来源 URL
    /// </summary>
    public readonly string SourceUrl;
    /// <summary>
    /// 来源页面修订号
    /// </summary>
    public readonly string SourceRevision;
    /// <summary>
    /// 来源说明
    /// </summary>
    public readonly string SourceNote;
   
    public const int __ID__ = 1998612293;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        CardId_Ref = tables.TbCard.GetOrDefault(CardId);
    }

    public override string ToString()
    {
        return "{ "
        + "cardId:" + CardId + ","
        + "structureType:" + StructureType + ","
        + "capacity:" + Capacity + ","
        + "cardCapDelta:" + CardCapDelta + ","
        + "isInfinite:" + IsInfinite + ","
        + "sellDuration:" + SellDuration + ","
        + "sellMultiplier:" + SellMultiplier + ","
        + "verifyStatus:" + VerifyStatus + ","
        + "sourceUrl:" + SourceUrl + ","
        + "sourceRevision:" + SourceRevision + ","
        + "sourceNote:" + SourceNote + ","
        + "}";
    }
}
}

