
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.stacklands
{
/// <summary>
/// 每个卡包的独立卡槽
/// </summary>
public partial class TbBoosterSlot
{
    private readonly System.Collections.Generic.Dictionary<string, stacklands.BoosterSlot> _dataMap;
    private readonly System.Collections.Generic.List<stacklands.BoosterSlot> _dataList;
    
    public TbBoosterSlot(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, stacklands.BoosterSlot>(n);
        _dataList = new System.Collections.Generic.List<stacklands.BoosterSlot>(n);
        for(int i = n ; i > 0 ; --i)
        {
            stacklands.BoosterSlot _v;
            _v = global::GameConfig.stacklands.BoosterSlot.DeserializeBoosterSlot(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, stacklands.BoosterSlot> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<stacklands.BoosterSlot> DataList => _dataList;

    public stacklands.BoosterSlot GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public stacklands.BoosterSlot Get(string key) => _dataMap[key];
    public stacklands.BoosterSlot this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

