
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.stacklands
{
/// <summary>
/// 主大陆八个购买卡包和两个特殊卡包
/// </summary>
public partial class TbBoosterPack
{
    private readonly System.Collections.Generic.Dictionary<string, stacklands.BoosterPack> _dataMap;
    private readonly System.Collections.Generic.List<stacklands.BoosterPack> _dataList;
    
    public TbBoosterPack(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, stacklands.BoosterPack>(n);
        _dataList = new System.Collections.Generic.List<stacklands.BoosterPack>(n);
        for(int i = n ; i > 0 ; --i)
        {
            stacklands.BoosterPack _v;
            _v = global::GameConfig.stacklands.BoosterPack.DeserializeBoosterPack(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, stacklands.BoosterPack> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<stacklands.BoosterPack> DataList => _dataList;

    public stacklands.BoosterPack GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public stacklands.BoosterPack Get(string key) => _dataMap[key];
    public stacklands.BoosterPack this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

