
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.stacklands
{
/// <summary>
/// 采集、探索、生产、出售和特殊交互入口
/// </summary>
public partial class TbCardAction
{
    private readonly System.Collections.Generic.Dictionary<string, stacklands.CardAction> _dataMap;
    private readonly System.Collections.Generic.List<stacklands.CardAction> _dataList;
    
    public TbCardAction(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, stacklands.CardAction>(n);
        _dataList = new System.Collections.Generic.List<stacklands.CardAction>(n);
        for(int i = n ; i > 0 ; --i)
        {
            stacklands.CardAction _v;
            _v = global::GameConfig.stacklands.CardAction.DeserializeCardAction(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, stacklands.CardAction> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<stacklands.CardAction> DataList => _dataList;

    public stacklands.CardAction GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public stacklands.CardAction Get(string key) => _dataMap[key];
    public stacklands.CardAction this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

