
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.stacklands
{
/// <summary>
/// 卡牌触发式特殊效果与局内限制
/// </summary>
public partial class TbCardEffect
{
    private readonly System.Collections.Generic.Dictionary<string, stacklands.CardEffect> _dataMap;
    private readonly System.Collections.Generic.List<stacklands.CardEffect> _dataList;
    
    public TbCardEffect(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, stacklands.CardEffect>(n);
        _dataList = new System.Collections.Generic.List<stacklands.CardEffect>(n);
        for(int i = n ; i > 0 ; --i)
        {
            stacklands.CardEffect _v;
            _v = global::GameConfig.stacklands.CardEffect.DeserializeCardEffect(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, stacklands.CardEffect> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<stacklands.CardEffect> DataList => _dataList;

    public stacklands.CardEffect GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public stacklands.CardEffect Get(string key) => _dataMap[key];
    public stacklands.CardEffect this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

