
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.stacklands
{
/// <summary>
/// Original 121 张卡牌主数据
/// </summary>
public partial class TbCard
{
    private readonly System.Collections.Generic.Dictionary<string, stacklands.Card> _dataMap;
    private readonly System.Collections.Generic.List<stacklands.Card> _dataList;
    
    public TbCard(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, stacklands.Card>(n);
        _dataList = new System.Collections.Generic.List<stacklands.Card>(n);
        for(int i = n ; i > 0 ; --i)
        {
            stacklands.Card _v;
            _v = global::GameConfig.stacklands.Card.DeserializeCard(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, stacklands.Card> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<stacklands.Card> DataList => _dataList;

    public stacklands.Card GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public stacklands.Card Get(string key) => _dataMap[key];
    public stacklands.Card this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

