
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.stacklands
{
/// <summary>
/// Original 三张装备定义
/// </summary>
public partial class TbEquipment
{
    private readonly System.Collections.Generic.Dictionary<string, stacklands.Equipment> _dataMap;
    private readonly System.Collections.Generic.List<stacklands.Equipment> _dataList;
    
    public TbEquipment(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, stacklands.Equipment>(n);
        _dataList = new System.Collections.Generic.List<stacklands.Equipment>(n);
        for(int i = n ; i > 0 ; --i)
        {
            stacklands.Equipment _v;
            _v = global::GameConfig.stacklands.Equipment.DeserializeEquipment(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.CardId, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, stacklands.Equipment> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<stacklands.Equipment> DataList => _dataList;

    public stacklands.Equipment GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public stacklands.Equipment Get(string key) => _dataMap[key];
    public stacklands.Equipment this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

