
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.stacklands
{
/// <summary>
/// 卡包、采集、探索和敌人掉落池
/// </summary>
public partial class TbLootPool
{
    private readonly System.Collections.Generic.Dictionary<string, stacklands.LootPool> _dataMap;
    private readonly System.Collections.Generic.List<stacklands.LootPool> _dataList;
    
    public TbLootPool(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, stacklands.LootPool>(n);
        _dataList = new System.Collections.Generic.List<stacklands.LootPool>(n);
        for(int i = n ; i > 0 ; --i)
        {
            stacklands.LootPool _v;
            _v = global::GameConfig.stacklands.LootPool.DeserializeLootPool(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, stacklands.LootPool> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<stacklands.LootPool> DataList => _dataList;

    public stacklands.LootPool GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public stacklands.LootPool Get(string key) => _dataMap[key];
    public stacklands.LootPool this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

