
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.stacklands
{
/// <summary>
/// 掉落池条目；未知概率不填零
/// </summary>
public partial class TbLootEntry
{
    private readonly System.Collections.Generic.Dictionary<string, stacklands.LootEntry> _dataMap;
    private readonly System.Collections.Generic.List<stacklands.LootEntry> _dataList;
    
    public TbLootEntry(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, stacklands.LootEntry>(n);
        _dataList = new System.Collections.Generic.List<stacklands.LootEntry>(n);
        for(int i = n ; i > 0 ; --i)
        {
            stacklands.LootEntry _v;
            _v = global::GameConfig.stacklands.LootEntry.DeserializeLootEntry(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, stacklands.LootEntry> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<stacklands.LootEntry> DataList => _dataList;

    public stacklands.LootEntry GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public stacklands.LootEntry Get(string key) => _dataMap[key];
    public stacklands.LootEntry this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

