
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.stacklands
{
/// <summary>
/// 地下墓穴和旅行商车确定性里程碑
/// </summary>
public partial class TbMilestone
{
    private readonly System.Collections.Generic.Dictionary<string, stacklands.Milestone> _dataMap;
    private readonly System.Collections.Generic.List<stacklands.Milestone> _dataList;
    
    public TbMilestone(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, stacklands.Milestone>(n);
        _dataList = new System.Collections.Generic.List<stacklands.Milestone>(n);
        for(int i = n ; i > 0 ; --i)
        {
            stacklands.Milestone _v;
            _v = global::GameConfig.stacklands.Milestone.DeserializeMilestone(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, stacklands.Milestone> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<stacklands.Milestone> DataList => _dataList;

    public stacklands.Milestone GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public stacklands.Milestone Get(string key) => _dataMap[key];
    public stacklands.Milestone this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

