
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.stacklands
{
/// <summary>
/// Original 基础版 56 项任务
/// </summary>
public partial class TbQuest
{
    private readonly System.Collections.Generic.Dictionary<string, stacklands.Quest> _dataMap;
    private readonly System.Collections.Generic.List<stacklands.Quest> _dataList;
    
    public TbQuest(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, stacklands.Quest>(n);
        _dataList = new System.Collections.Generic.List<stacklands.Quest>(n);
        for(int i = n ; i > 0 ; --i)
        {
            stacklands.Quest _v;
            _v = global::GameConfig.stacklands.Quest.DeserializeQuest(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, stacklands.Quest> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<stacklands.Quest> DataList => _dataList;

    public stacklands.Quest GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public stacklands.Quest Get(string key) => _dataMap[key];
    public stacklands.Quest this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

