
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.stacklands
{
/// <summary>
/// 32 张 Original 点子及炉灶料理变体
/// </summary>
public partial class TbRecipe
{
    private readonly System.Collections.Generic.Dictionary<string, stacklands.Recipe> _dataMap;
    private readonly System.Collections.Generic.List<stacklands.Recipe> _dataList;
    
    public TbRecipe(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, stacklands.Recipe>(n);
        _dataList = new System.Collections.Generic.List<stacklands.Recipe>(n);
        for(int i = n ; i > 0 ; --i)
        {
            stacklands.Recipe _v;
            _v = global::GameConfig.stacklands.Recipe.DeserializeRecipe(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, stacklands.Recipe> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<stacklands.Recipe> DataList => _dataList;

    public stacklands.Recipe GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public stacklands.Recipe Get(string key) => _dataMap[key];
    public stacklands.Recipe this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

