
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.stacklands
{
/// <summary>
/// 建筑、资源节点和特殊结构参数
/// </summary>
public partial class TbStructure
{
    private readonly System.Collections.Generic.Dictionary<string, stacklands.Structure> _dataMap;
    private readonly System.Collections.Generic.List<stacklands.Structure> _dataList;
    
    public TbStructure(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, stacklands.Structure>(n);
        _dataList = new System.Collections.Generic.List<stacklands.Structure>(n);
        for(int i = n ; i > 0 ; --i)
        {
            stacklands.Structure _v;
            _v = global::GameConfig.stacklands.Structure.DeserializeStructure(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.CardId, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, stacklands.Structure> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<stacklands.Structure> DataList => _dataList;

    public stacklands.Structure GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public stacklands.Structure Get(string key) => _dataMap[key];
    public stacklands.Structure this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

