
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.stacklands
{
/// <summary>
/// 村民、友好动物和敌对单位基础属性
/// </summary>
public partial class TbUnit
{
    private readonly System.Collections.Generic.Dictionary<string, stacklands.Unit> _dataMap;
    private readonly System.Collections.Generic.List<stacklands.Unit> _dataList;
    
    public TbUnit(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, stacklands.Unit>(n);
        _dataList = new System.Collections.Generic.List<stacklands.Unit>(n);
        for(int i = n ; i > 0 ; --i)
        {
            stacklands.Unit _v;
            _v = global::GameConfig.stacklands.Unit.DeserializeUnit(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.CardId, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, stacklands.Unit> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<stacklands.Unit> DataList => _dataList;

    public stacklands.Unit GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public stacklands.Unit Get(string key) => _dataMap[key];
    public stacklands.Unit this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

