
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.stacklands
{
/// <summary>
/// Original 主大陆全局规则
/// </summary>
public partial class TbWorldRule
{
    private readonly System.Collections.Generic.Dictionary<string, stacklands.WorldRule> _dataMap;
    private readonly System.Collections.Generic.List<stacklands.WorldRule> _dataList;
    
    public TbWorldRule(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, stacklands.WorldRule>(n);
        _dataList = new System.Collections.Generic.List<stacklands.WorldRule>(n);
        for(int i = n ; i > 0 ; --i)
        {
            stacklands.WorldRule _v;
            _v = global::GameConfig.stacklands.WorldRule.DeserializeWorldRule(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, stacklands.WorldRule> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<stacklands.WorldRule> DataList => _dataList;

    public stacklands.WorldRule GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public stacklands.WorldRule Get(string key) => _dataMap[key];
    public stacklands.WorldRule this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

