
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.stacklands
{
public sealed partial class Unit : Luban.BeanBase
{
    public Unit(ByteBuf _buf) 
    {
        CardId = _buf.ReadString();
        CardId_Ref = null;
        Faction = (stacklands.EUnitFaction)_buf.ReadInt();
        if(_buf.ReadBool()){ FoodPerMoon = _buf.ReadInt(); } else { FoodPerMoon = null; }
        if(_buf.ReadBool()){ MaxHp = _buf.ReadInt(); } else { MaxHp = null; }
        if(_buf.ReadBool()){ CombatLevel = _buf.ReadInt(); } else { CombatLevel = null; }
        AttackType = (stacklands.EAttackType)_buf.ReadInt();
        if(_buf.ReadBool()){ AttackInterval = _buf.ReadFloat(); } else { AttackInterval = null; }
        if(_buf.ReadBool()){ HitChance = _buf.ReadFloat(); } else { HitChance = null; }
        if(_buf.ReadBool()){ DamageMin = _buf.ReadInt(); } else { DamageMin = null; }
        if(_buf.ReadBool()){ DamageMax = _buf.ReadInt(); } else { DamageMax = null; }
        if(_buf.ReadBool()){ Defense = _buf.ReadInt(); } else { Defense = null; }
        if(_buf.ReadBool()){ CritChance = _buf.ReadFloat(); } else { CritChance = null; }
        if(_buf.ReadBool()){ WorkSpeed = _buf.ReadFloat(); } else { WorkSpeed = null; }
        if(_buf.ReadBool()){ ExploreSpeed = _buf.ReadFloat(); } else { ExploreSpeed = null; }
        if(_buf.ReadBool()){ DeathResultCardId = _buf.ReadString(); } else { DeathResultCardId = null; }
        VerifyStatus = (stacklands.EVerifyStatus)_buf.ReadInt();
        SourceUrl = _buf.ReadString();
        SourceRevision = _buf.ReadString();
        SourceNote = _buf.ReadString();
    }

    public static Unit DeserializeUnit(ByteBuf _buf)
    {
        return new stacklands.Unit(_buf);
    }

    /// <summary>
    /// 单位卡牌
    /// </summary>
    public readonly string CardId;
    public stacklands.Card CardId_Ref;
    /// <summary>
    /// 阵营
    /// </summary>
    public readonly stacklands.EUnitFaction Faction;
    /// <summary>
    /// 每月食物需求
    /// </summary>
    public readonly int? FoodPerMoon;
    /// <summary>
    /// 最大生命
    /// </summary>
    public readonly int? MaxHp;
    /// <summary>
    /// 战斗等级
    /// </summary>
    public readonly int? CombatLevel;
    /// <summary>
    /// 攻击类型
    /// </summary>
    public readonly stacklands.EAttackType AttackType;
    /// <summary>
    /// 攻击间隔
    /// </summary>
    public readonly float? AttackInterval;
    /// <summary>
    /// 命中率
    /// </summary>
    public readonly float? HitChance;
    /// <summary>
    /// 最小伤害
    /// </summary>
    public readonly int? DamageMin;
    /// <summary>
    /// 最大伤害
    /// </summary>
    public readonly int? DamageMax;
    /// <summary>
    /// 防御
    /// </summary>
    public readonly int? Defense;
    /// <summary>
    /// 暴击率
    /// </summary>
    public readonly float? CritChance;
    /// <summary>
    /// 工作速度倍率
    /// </summary>
    public readonly float? WorkSpeed;
    /// <summary>
    /// 探索速度倍率
    /// </summary>
    public readonly float? ExploreSpeed;
    /// <summary>
    /// 死亡结果卡牌
    /// </summary>
    public readonly string DeathResultCardId;
    /// <summary>
    /// 核验状态
    /// </summary>
    public readonly stacklands.EVerifyStatus VerifyStatus;
    /// <summary>
    /// 来源 URL
    /// </summary>
    public readonly string SourceUrl;
    /// <summary>
    /// 来源页面修订号
    /// </summary>
    public readonly string SourceRevision;
    /// <summary>
    /// 来源说明
    /// </summary>
    public readonly string SourceNote;
   
    public const int __ID__ = -1685633934;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        CardId_Ref = tables.TbCard.GetOrDefault(CardId);
    }

    public override string ToString()
    {
        return "{ "
        + "cardId:" + CardId + ","
        + "faction:" + Faction + ","
        + "foodPerMoon:" + FoodPerMoon + ","
        + "maxHp:" + MaxHp + ","
        + "combatLevel:" + CombatLevel + ","
        + "attackType:" + AttackType + ","
        + "attackInterval:" + AttackInterval + ","
        + "hitChance:" + HitChance + ","
        + "damageMin:" + DamageMin + ","
        + "damageMax:" + DamageMax + ","
        + "defense:" + Defense + ","
        + "critChance:" + CritChance + ","
        + "workSpeed:" + WorkSpeed + ","
        + "exploreSpeed:" + ExploreSpeed + ","
        + "deathResultCardId:" + DeathResultCardId + ","
        + "verifyStatus:" + VerifyStatus + ","
        + "sourceUrl:" + SourceUrl + ","
        + "sourceRevision:" + SourceRevision + ","
        + "sourceNote:" + SourceNote + ","
        + "}";
    }
}
}

