
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.stacklands
{
public sealed partial class WorldRule : Luban.BeanBase
{
    public WorldRule(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        MoonShortSeconds = _buf.ReadInt();
        MoonNormalSeconds = _buf.ReadInt();
        MoonLongSeconds = _buf.ReadInt();
        if(_buf.ReadBool()){ BaseCardCap = _buf.ReadInt(); } else { BaseCardCap = null; }
        {int n0 = _buf.ReadSize(); FeedingPriority = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); FeedingPriority.Add(_e0);}}
        {int n0 = _buf.ReadSize(); SpeedOptions = new System.Collections.Generic.List<float>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { float _e0;  _e0 = _buf.ReadFloat(); SpeedOptions.Add(_e0);}}
        PortalStartMoon = _buf.ReadInt();
        PortalInterval = _buf.ReadInt();
        RarePortalFrequency = _buf.ReadInt();
        PortalDelay = _buf.ReadInt();
        ThreatCapMoon = _buf.ReadInt();
        CartStartMoon = _buf.ReadInt();
        CartChance = _buf.ReadFloat();
        CartGuaranteeMoon = _buf.ReadInt();
        CartPrice = _buf.ReadInt();
        CartGobletPurchase = _buf.ReadInt();
        CombatAdvantageMultiplier = _buf.ReadFloat();
        VerifyStatus = (stacklands.EVerifyStatus)_buf.ReadInt();
        SourceUrl = _buf.ReadString();
        SourceRevision = _buf.ReadString();
        SourceNote = _buf.ReadString();
        MaxStackSize = _buf.ReadInt();
        SecondVillagerGuaranteePack = _buf.ReadInt();
        SingleVillagerPackChance = _buf.ReadFloat();
        PortalBaseThreat = _buf.ReadInt();
        PortalThreatPerInterval = _buf.ReadInt();
        RarePortalMultiplier = _buf.ReadFloat();
    }

    public static WorldRule DeserializeWorldRule(ByteBuf _buf)
    {
        return new stacklands.WorldRule(_buf);
    }

    /// <summary>
    /// 规则集 ID
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 短月秒数
    /// </summary>
    public readonly int MoonShortSeconds;
    /// <summary>
    /// 普通月秒数
    /// </summary>
    public readonly int MoonNormalSeconds;
    /// <summary>
    /// 长月秒数
    /// </summary>
    public readonly int MoonLongSeconds;
    /// <summary>
    /// 基础卡牌上限
    /// </summary>
    public readonly int? BaseCardCap;
    /// <summary>
    /// 喂食优先级
    /// </summary>
    public readonly System.Collections.Generic.List<string> FeedingPriority;
    /// <summary>
    /// 速度选项
    /// </summary>
    public readonly System.Collections.Generic.List<float> SpeedOptions;
    /// <summary>
    /// 传送门起始月
    /// </summary>
    public readonly int PortalStartMoon;
    /// <summary>
    /// 传送门间隔月
    /// </summary>
    public readonly int PortalInterval;
    /// <summary>
    /// 稀有传送门频率
    /// </summary>
    public readonly int RarePortalFrequency;
    /// <summary>
    /// 传送门延迟秒
    /// </summary>
    public readonly int PortalDelay;
    /// <summary>
    /// 威胁封顶月
    /// </summary>
    public readonly int ThreatCapMoon;
    /// <summary>
    /// 商车起始月
    /// </summary>
    public readonly int CartStartMoon;
    /// <summary>
    /// 商车出现概率
    /// </summary>
    public readonly float CartChance;
    /// <summary>
    /// 商车保底月
    /// </summary>
    public readonly int CartGuaranteeMoon;
    /// <summary>
    /// 商车价格
    /// </summary>
    public readonly int CartPrice;
    /// <summary>
    /// 金杯购买次数
    /// </summary>
    public readonly int CartGobletPurchase;
    /// <summary>
    /// 克制伤害倍率
    /// </summary>
    public readonly float CombatAdvantageMultiplier;
    /// <summary>
    /// 核验状态
    /// </summary>
    public readonly stacklands.EVerifyStatus VerifyStatus;
    /// <summary>
    /// 来源 URL
    /// </summary>
    public readonly string SourceUrl;
    /// <summary>
    /// 来源页面修订号
    /// </summary>
    public readonly string SourceRevision;
    /// <summary>
    /// 来源说明
    /// </summary>
    public readonly string SourceNote;
    /// <summary>
    /// 牌堆最大卡数
    /// </summary>
    public readonly int MaxStackSize;
    /// <summary>
    /// 第二村民保底购买次数
    /// </summary>
    public readonly int SecondVillagerGuaranteePack;
    /// <summary>
    /// 仅一名成人时村民概率
    /// </summary>
    public readonly float SingleVillagerPackChance;
    /// <summary>
    /// 普通传送门基础威胁
    /// </summary>
    public readonly int PortalBaseThreat;
    /// <summary>
    /// 每个传送门间隔增加威胁
    /// </summary>
    public readonly int PortalThreatPerInterval;
    /// <summary>
    /// 稀有传送门威胁倍率
    /// </summary>
    public readonly float RarePortalMultiplier;
   
    public const int __ID__ = -1318107264;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "moonShortSeconds:" + MoonShortSeconds + ","
        + "moonNormalSeconds:" + MoonNormalSeconds + ","
        + "moonLongSeconds:" + MoonLongSeconds + ","
        + "baseCardCap:" + BaseCardCap + ","
        + "feedingPriority:" + Luban.StringUtil.CollectionToString(FeedingPriority) + ","
        + "speedOptions:" + Luban.StringUtil.CollectionToString(SpeedOptions) + ","
        + "portalStartMoon:" + PortalStartMoon + ","
        + "portalInterval:" + PortalInterval + ","
        + "rarePortalFrequency:" + RarePortalFrequency + ","
        + "portalDelay:" + PortalDelay + ","
        + "threatCapMoon:" + ThreatCapMoon + ","
        + "cartStartMoon:" + CartStartMoon + ","
        + "cartChance:" + CartChance + ","
        + "cartGuaranteeMoon:" + CartGuaranteeMoon + ","
        + "cartPrice:" + CartPrice + ","
        + "cartGobletPurchase:" + CartGobletPurchase + ","
        + "combatAdvantageMultiplier:" + CombatAdvantageMultiplier + ","
        + "verifyStatus:" + VerifyStatus + ","
        + "sourceUrl:" + SourceUrl + ","
        + "sourceRevision:" + SourceRevision + ","
        + "sourceNote:" + SourceNote + ","
        + "maxStackSize:" + MaxStackSize + ","
        + "secondVillagerGuaranteePack:" + SecondVillagerGuaranteePack + ","
        + "singleVillagerPackChance:" + SingleVillagerPackChance + ","
        + "portalBaseThreat:" + PortalBaseThreat + ","
        + "portalThreatPerInterval:" + PortalThreatPerInterval + ","
        + "rarePortalMultiplier:" + RarePortalMultiplier + ","
        + "}";
    }
}
}

