
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.carnival
{
public sealed partial class CardEnhancementConfig : Luban.BeanBase
{
    public CardEnhancementConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        Name = _buf.ReadString();
        Desc = _buf.ReadString();
        Chips = _buf.ReadInt();
        AdditiveMultiplier = _buf.ReadFloat();
        MultiplierFactor = _buf.ReadFloat();
        BreakChance = _buf.ReadFloat();
    }

    public static CardEnhancementConfig DeserializeCardEnhancementConfig(ByteBuf _buf)
    {
        return new carnival.CardEnhancementConfig(_buf);
    }

    /// <summary>
    /// 对应CarnivalCardEnhancement枚举
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 显示名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 作用说明
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 额外筹码
    /// </summary>
    public readonly int Chips;
    /// <summary>
    /// 额外加法倍率
    /// </summary>
    public readonly float AdditiveMultiplier;
    /// <summary>
    /// 最终倍率乘数
    /// </summary>
    public readonly float MultiplierFactor;
    /// <summary>
    /// 结算后碎裂概率
    /// </summary>
    public readonly float BreakChance;
   
    public const int __ID__ = 1744385378;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "chips:" + Chips + ","
        + "additiveMultiplier:" + AdditiveMultiplier + ","
        + "multiplierFactor:" + MultiplierFactor + ","
        + "breakChance:" + BreakChance + ","
        + "}";
    }
}
}

