
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.carnival
{
public sealed partial class ConsumableConfig : Luban.BeanBase
{
    public ConsumableConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        Name = _buf.ReadString();
        Family = _buf.ReadString();
        Desc = _buf.ReadString();
        Cost = _buf.ReadInt();
        Action = _buf.ReadString();
        MaxSelected = _buf.ReadInt();
        Enhancement = _buf.ReadString();
        HandKind = _buf.ReadString();
        Suit = _buf.ReadString();
        Amount = _buf.ReadInt();
        SecondaryAmount = _buf.ReadInt();
        BoolValue = _buf.ReadBool();
    }

    public static ConsumableConfig DeserializeConsumableConfig(ByteBuf _buf)
    {
        return new carnival.ConsumableConfig(_buf);
    }

    /// <summary>
    /// 唯一ID
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// Tarot/Planet/Spectral
    /// </summary>
    public readonly string Family;
    /// <summary>
    /// 作用说明
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 商店售价
    /// </summary>
    public readonly int Cost;
    /// <summary>
    /// 行为执行器
    /// </summary>
    public readonly string Action;
    /// <summary>
    /// 最多选择牌数
    /// </summary>
    public readonly int MaxSelected;
    /// <summary>
    /// 目标强化，None表示无
    /// </summary>
    public readonly string Enhancement;
    /// <summary>
    /// 目标牌型，None表示无
    /// </summary>
    public readonly string HandKind;
    /// <summary>
    /// 目标花色，None表示无
    /// </summary>
    public readonly string Suit;
    /// <summary>
    /// 主要整数参数
    /// </summary>
    public readonly int Amount;
    /// <summary>
    /// 次要整数参数
    /// </summary>
    public readonly int SecondaryAmount;
    /// <summary>
    /// 布尔参数
    /// </summary>
    public readonly bool BoolValue;
   
    public const int __ID__ = 1397729761;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "family:" + Family + ","
        + "desc:" + Desc + ","
        + "cost:" + Cost + ","
        + "action:" + Action + ","
        + "maxSelected:" + MaxSelected + ","
        + "enhancement:" + Enhancement + ","
        + "handKind:" + HandKind + ","
        + "suit:" + Suit + ","
        + "amount:" + Amount + ","
        + "secondaryAmount:" + SecondaryAmount + ","
        + "boolValue:" + BoolValue + ","
        + "}";
    }
}
}

