
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.carnival
{
public sealed partial class PerformerConfig : Luban.BeanBase
{
    public PerformerConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        Name = _buf.ReadString();
        ShortName = _buf.ReadString();
        Icon = _buf.ReadString();
        Desc = _buf.ReadString();
        Cost = _buf.ReadInt();
        Rarity = _buf.ReadString();
        IsStarting = _buf.ReadBool();
        Effect = _buf.ReadString();
        EffectValue = _buf.ReadFloat();
        ConditionValue = _buf.ReadInt();
        HandKind = _buf.ReadString();
        Suit = _buf.ReadString();
    }

    public static PerformerConfig DeserializePerformerConfig(ByteBuf _buf)
    {
        return new carnival.PerformerConfig(_buf);
    }

    /// <summary>
    /// 唯一ID
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 完整名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 卡面短名称
    /// </summary>
    public readonly string ShortName;
    /// <summary>
    /// 卡面图标
    /// </summary>
    public readonly string Icon;
    /// <summary>
    /// 作用说明
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 商店售价
    /// </summary>
    public readonly int Cost;
    /// <summary>
    /// 稀有度
    /// </summary>
    public readonly string Rarity;
    /// <summary>
    /// 是否为开局表演者
    /// </summary>
    public readonly bool IsStarting;
    /// <summary>
    /// 效果执行器
    /// </summary>
    public readonly string Effect;
    /// <summary>
    /// 主要效果数值
    /// </summary>
    public readonly float EffectValue;
    /// <summary>
    /// 条件参数
    /// </summary>
    public readonly int ConditionValue;
    /// <summary>
    /// 目标牌型，None表示无
    /// </summary>
    public readonly string HandKind;
    /// <summary>
    /// 目标花色，None表示无
    /// </summary>
    public readonly string Suit;
   
    public const int __ID__ = -1343140140;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "shortName:" + ShortName + ","
        + "icon:" + Icon + ","
        + "desc:" + Desc + ","
        + "cost:" + Cost + ","
        + "rarity:" + Rarity + ","
        + "isStarting:" + IsStarting + ","
        + "effect:" + Effect + ","
        + "effectValue:" + EffectValue + ","
        + "conditionValue:" + ConditionValue + ","
        + "handKind:" + HandKind + ","
        + "suit:" + Suit + ","
        + "}";
    }
}
}

