
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.carnival
{
public sealed partial class PerformerConfig : Luban.BeanBase
{
    public PerformerConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        Name = _buf.ReadString();
        MythicName = _buf.ReadString();
        ShortName = _buf.ReadString();
        Icon = _buf.ReadString();
        Desc = _buf.ReadString();
        Cost = _buf.ReadInt();
        Rarity = _buf.ReadString();
        IsStarting = _buf.ReadBool();
        Effect = _buf.ReadString();
        EffectValue = _buf.ReadFloat();
        ConditionValue = _buf.ReadInt();
        HandKind = _buf.ReadString();
        Suit = _buf.ReadString();
        OriginalOrder = _buf.ReadInt();
        NameEn = _buf.ReadString();
        DescEn = _buf.ReadString();
        UnlockRequirement = _buf.ReadString();
        UnlockedByDefault = _buf.ReadBool();
        Activation = _buf.ReadString();
        JokerType = _buf.ReadString();
        BlueprintCompatible = _buf.ReadBool();
        PerishableCompatible = _buf.ReadBool();
        EternalCompatible = _buf.ReadBool();
        Parameters = _buf.ReadString();
        SourceUrl = _buf.ReadString();
    }

    public static PerformerConfig DeserializePerformerConfig(ByteBuf _buf)
    {
        return new carnival.PerformerConfig(_buf);
    }

    /// <summary>
    /// 卡牌内部 ID
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 简体中文名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 中国神话仙侠题材神器或法宝名称（按卡牌功能与原版稀有度匹配，且全表唯一）
    /// </summary>
    public readonly string MythicName;
    /// <summary>
    /// 简短名称
    /// </summary>
    public readonly string ShortName;
    /// <summary>
    /// 界面图标
    /// </summary>
    public readonly string Icon;
    /// <summary>
    /// 简体中文原版效果
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 原版基础价格
    /// </summary>
    public readonly int Cost;
    /// <summary>
    /// 原版稀有度
    /// </summary>
    public readonly string Rarity;
    /// <summary>
    /// 是否开局直接持有
    /// </summary>
    public readonly bool IsStarting;
    /// <summary>
    /// 运行时效果执行器
    /// </summary>
    public readonly string Effect;
    /// <summary>
    /// 通用效果参数
    /// </summary>
    public readonly float EffectValue;
    /// <summary>
    /// 通用条件参数
    /// </summary>
    public readonly int ConditionValue;
    /// <summary>
    /// 关联牌型；None 表示无
    /// </summary>
    public readonly string HandKind;
    /// <summary>
    /// 关联花色；None 表示无
    /// </summary>
    public readonly string Suit;
    /// <summary>
    /// 原版收藏顺序
    /// </summary>
    public readonly int OriginalOrder;
    /// <summary>
    /// 英文原名
    /// </summary>
    public readonly string NameEn;
    /// <summary>
    /// 英文原版效果
    /// </summary>
    public readonly string DescEn;
    /// <summary>
    /// 原版解锁条件
    /// </summary>
    public readonly string UnlockRequirement;
    /// <summary>
    /// 原版是否默认解锁
    /// </summary>
    public readonly bool UnlockedByDefault;
    /// <summary>
    /// 原版触发阶段
    /// </summary>
    public readonly string Activation;
    /// <summary>
    /// 原版效果类别
    /// </summary>
    public readonly string JokerType;
    /// <summary>
    /// 是否可被蓝图或头脑风暴复制
    /// </summary>
    public readonly bool BlueprintCompatible;
    /// <summary>
    /// 是否兼容易腐贴纸
    /// </summary>
    public readonly bool PerishableCompatible;
    /// <summary>
    /// 是否兼容永恒贴纸
    /// </summary>
    public readonly bool EternalCompatible;
    /// <summary>
    /// 从原版 game.lua 提取的效果参数
    /// </summary>
    public readonly string Parameters;
    /// <summary>
    /// 数据来源
    /// </summary>
    public readonly string SourceUrl;
   
    public const int __ID__ = -1343140140;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "mythicName:" + MythicName + ","
        + "shortName:" + ShortName + ","
        + "icon:" + Icon + ","
        + "desc:" + Desc + ","
        + "cost:" + Cost + ","
        + "rarity:" + Rarity + ","
        + "isStarting:" + IsStarting + ","
        + "effect:" + Effect + ","
        + "effectValue:" + EffectValue + ","
        + "conditionValue:" + ConditionValue + ","
        + "handKind:" + HandKind + ","
        + "suit:" + Suit + ","
        + "originalOrder:" + OriginalOrder + ","
        + "nameEn:" + NameEn + ","
        + "descEn:" + DescEn + ","
        + "unlockRequirement:" + UnlockRequirement + ","
        + "unlockedByDefault:" + UnlockedByDefault + ","
        + "activation:" + Activation + ","
        + "jokerType:" + JokerType + ","
        + "blueprintCompatible:" + BlueprintCompatible + ","
        + "perishableCompatible:" + PerishableCompatible + ","
        + "eternalCompatible:" + EternalCompatible + ","
        + "parameters:" + Parameters + ","
        + "sourceUrl:" + SourceUrl + ","
        + "}";
    }
}
}

