
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.carnival
{
/// <summary>
/// 扑克牌强化效果
/// </summary>
public partial class TbCardEnhancement
{
    private readonly System.Collections.Generic.Dictionary<string, carnival.CardEnhancementConfig> _dataMap;
    private readonly System.Collections.Generic.List<carnival.CardEnhancementConfig> _dataList;
    
    public TbCardEnhancement(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, carnival.CardEnhancementConfig>(n);
        _dataList = new System.Collections.Generic.List<carnival.CardEnhancementConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            carnival.CardEnhancementConfig _v;
            _v = global::GameConfig.carnival.CardEnhancementConfig.DeserializeCardEnhancementConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, carnival.CardEnhancementConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<carnival.CardEnhancementConfig> DataList => _dataList;

    public carnival.CardEnhancementConfig GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public carnival.CardEnhancementConfig Get(string key) => _dataMap[key];
    public carnival.CardEnhancementConfig this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

