
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.carnival
{
/// <summary>
/// 马戏牌局消耗牌
/// </summary>
public partial class TbConsumable
{
    private readonly System.Collections.Generic.Dictionary<string, carnival.ConsumableConfig> _dataMap;
    private readonly System.Collections.Generic.List<carnival.ConsumableConfig> _dataList;
    
    public TbConsumable(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, carnival.ConsumableConfig>(n);
        _dataList = new System.Collections.Generic.List<carnival.ConsumableConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            carnival.ConsumableConfig _v;
            _v = global::GameConfig.carnival.ConsumableConfig.DeserializeConsumableConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, carnival.ConsumableConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<carnival.ConsumableConfig> DataList => _dataList;

    public carnival.ConsumableConfig GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public carnival.ConsumableConfig Get(string key) => _dataMap[key];
    public carnival.ConsumableConfig this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

