// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: metadream/app/her/common/v1/app_her_common_v1_resources.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Metadream.App.Her.Common.V1 {

  /// <summary>Holder for reflection information generated from metadream/app/her/common/v1/app_her_common_v1_resources.proto</summary>
  public static partial class AppHerCommonV1ResourcesReflection {

    #region Descriptor
    /// <summary>File descriptor for metadream/app/her/common/v1/app_her_common_v1_resources.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AppHerCommonV1ResourcesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cj1tZXRhZHJlYW0vYXBwL2hlci9jb21tb24vdjEvYXBwX2hlcl9jb21tb25f",
            "djFfcmVzb3VyY2VzLnByb3RvEhttZXRhZHJlYW0uYXBwLmhlci5jb21tb24u",
            "djEqsgMKDEhlckVycm9yQ29kZRImCiJIRVJfRVJST1JfQ09ERV9TVUNDRVNT",
            "X1VOU1BFQ0lGSUVEEAASJgogSEVSX0VSUk9SX0NPREVfSU5WQUxJRF9QQVJB",
            "TUVURVIQseoBEiEKG0hFUl9FUlJPUl9DT0RFX0xPR0lOX0ZBSUxFRBCy6gES",
            "IgocSEVSX0VSUk9SX0NPREVfTE9HT1VUX0ZBSUxFRBCz6gESIwodSEVSX0VS",
            "Uk9SX0NPREVfREVTVFJPWV9GQUlMRUQQtOoBEiUKH0hFUl9FUlJPUl9DT0RF",
            "X1JUQ19UT0tFTl9GQUlMRUQQlOsBEicKIUhFUl9FUlJPUl9DT0RFX1ZPSUNF",
            "X1NUQVJUX0ZBSUxFRBCV6wESJgogSEVSX0VSUk9SX0NPREVfVk9JQ0VfU1RP",
            "UF9GQUlMRUQQlusBEiUKH0hFUl9FUlJPUl9DT0RFX1RFWFRfQ0hBVF9GQUlM",
            "RUQQl+sBEiMKHUhFUl9FUlJPUl9DT0RFX1VTRVJfTk9UX0ZPVU5EEPjrARIi",
            "ChxIRVJfRVJST1JfQ09ERV9IRVJfTk9UX0ZPVU5EEPnrAUKXAQofY29tLm1l",
            "dGFkcmVhbS5hcHAuaGVyLmNvbW1vbi52MVABWkpnaXRsYWIuYm9uZGVlLWlu",
            "Yy5jb20vaWRsL2J1ZmJ1aWxkL2dvL3Byb3RvL21ldGFkcmVhbS9hcHAvaGVy",
            "L2NvbW1vbi92MTt2MaICB01BUEhFUjGqAhtNZXRhZHJlYW0uQXBwLkhlci5D",
            "b21tb24uVjFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Metadream.App.Her.Common.V1.HerErrorCode), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum HerErrorCode {
    /// <summary>
    /// 成功
    /// </summary>
    [pbr::OriginalName("HER_ERROR_CODE_SUCCESS_UNSPECIFIED")] SuccessUnspecified = 0,
    /// <summary>
    /// 参数错误
    /// </summary>
    [pbr::OriginalName("HER_ERROR_CODE_INVALID_PARAMETER")] InvalidParameter = 30001,
    /// <summary>
    /// 登录失败
    /// </summary>
    [pbr::OriginalName("HER_ERROR_CODE_LOGIN_FAILED")] LoginFailed = 30002,
    /// <summary>
    /// 登出失败
    /// </summary>
    [pbr::OriginalName("HER_ERROR_CODE_LOGOUT_FAILED")] LogoutFailed = 30003,
    /// <summary>
    /// 注销失败
    /// </summary>
    [pbr::OriginalName("HER_ERROR_CODE_DESTROY_FAILED")] DestroyFailed = 30004,
    /// <summary>
    /// 获取RTC Token失败
    /// </summary>
    [pbr::OriginalName("HER_ERROR_CODE_RTC_TOKEN_FAILED")] RtcTokenFailed = 30100,
    /// <summary>
    /// 语音通话启动失败
    /// </summary>
    [pbr::OriginalName("HER_ERROR_CODE_VOICE_START_FAILED")] VoiceStartFailed = 30101,
    /// <summary>
    /// 语音通话停止失败
    /// </summary>
    [pbr::OriginalName("HER_ERROR_CODE_VOICE_STOP_FAILED")] VoiceStopFailed = 30102,
    /// <summary>
    /// 文本聊天失败
    /// </summary>
    [pbr::OriginalName("HER_ERROR_CODE_TEXT_CHAT_FAILED")] TextChatFailed = 30103,
    /// <summary>
    /// 用户不存在
    /// </summary>
    [pbr::OriginalName("HER_ERROR_CODE_USER_NOT_FOUND")] UserNotFound = 30200,
    /// <summary>
    /// agent不存在
    /// </summary>
    [pbr::OriginalName("HER_ERROR_CODE_HER_NOT_FOUND")] HerNotFound = 30201,
  }

  #endregion

}

#endregion Designer generated code
