// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: metadream/app/her/v1/app_her_v1_services.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Metadream.App.Her.V1 {

  /// <summary>Holder for reflection information generated from metadream/app/her/v1/app_her_v1_services.proto</summary>
  public static partial class AppHerV1ServicesReflection {

    #region Descriptor
    /// <summary>File descriptor for metadream/app/her/v1/app_her_v1_services.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AppHerV1ServicesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ci5tZXRhZHJlYW0vYXBwL2hlci92MS9hcHBfaGVyX3YxX3NlcnZpY2VzLnBy",
            "b3RvEhRtZXRhZHJlYW0uYXBwLmhlci52MRovbWV0YWRyZWFtL2FwcC9oZXIv",
            "djEvYXBwX2hlcl92MV9yZXNvdXJjZXMucHJvdG8yXwoOSGVyVGVzdFNlcnZp",
            "Y2USTQoEVGVzdBIhLm1ldGFkcmVhbS5hcHAuaGVyLnYxLlRlc3RSZXF1ZXN0",
            "GiIubWV0YWRyZWFtLmFwcC5oZXIudjEuVGVzdFJlc3BvbnNlQpcBChhjb20u",
            "bWV0YWRyZWFtLmFwcC5oZXIudjFCE0hlclRlc3RTZXJ2aWNlUHJvdG9QAVpD",
            "Z2l0bGFiLmJvbmRlZS1pbmMuY29tL2lkbC9idWZidWlsZC9nby9wcm90by9t",
            "ZXRhZHJlYW0vYXBwL2hlci92MTt2MaICB01BUEhFUjGqAhRNZXRhZHJlYW0u",
            "QXBwLkhlci5WMWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Metadream.App.Her.V1.AppHerV1ResourcesReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
