// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: metadream/app/her/avatar/v1/app_her_avatar_v1_services.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Metadream.App.Her.Avatar.V1 {

  /// <summary>Holder for reflection information generated from metadream/app/her/avatar/v1/app_her_avatar_v1_services.proto</summary>
  public static partial class AppHerAvatarV1ServicesReflection {

    #region Descriptor
    /// <summary>File descriptor for metadream/app/her/avatar/v1/app_her_avatar_v1_services.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AppHerAvatarV1ServicesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjxtZXRhZHJlYW0vYXBwL2hlci9hdmF0YXIvdjEvYXBwX2hlcl9hdmF0YXJf",
            "djFfc2VydmljZXMucHJvdG8SG21ldGFkcmVhbS5hcHAuaGVyLmF2YXRhci52",
            "MRocZ29vZ2xlL2FwaS9hbm5vdGF0aW9ucy5wcm90bxo9bWV0YWRyZWFtL2Fw",
            "cC9oZXIvYXZhdGFyL3YxL2FwcF9oZXJfYXZhdGFyX3YxX3Jlc291cmNlcy5w",
            "cm90bzKeDgoQSGVyQXZhdGFyU2VydmljZRLBAQoVTG9naW5PclJlZ2lzdGVy",
            "QnlDb2RlEjkubWV0YWRyZWFtLmFwcC5oZXIuYXZhdGFyLnYxLkxvZ2luT3JS",
            "ZWdpc3RlckJ5Q29kZVJlcXVlc3QaOi5tZXRhZHJlYW0uYXBwLmhlci5hdmF0",
            "YXIudjEuTG9naW5PclJlZ2lzdGVyQnlDb2RlUmVzcG9uc2UiMYLT5JMCKyIm",
            "L2hlci1hdmF0YXIvbG9naW5fYW5kX3JlZ2lzdGVyX2J5X2NvZGU6ASoSkgEK",
            "CkxvZ2luQnlQd2QSLi5tZXRhZHJlYW0uYXBwLmhlci5hdmF0YXIudjEuTG9n",
            "aW5CeVB3ZFJlcXVlc3QaLy5tZXRhZHJlYW0uYXBwLmhlci5hdmF0YXIudjEu",
            "TG9naW5CeVB3ZFJlc3BvbnNlIiOC0+STAh0iGC9oZXItYXZhdGFyL2xvZ2lu",
            "X2J5X3B3ZDoBKhKeAQoNTG9naW5CeUdvb2dsZRIxLm1ldGFkcmVhbS5hcHAu",
            "aGVyLmF2YXRhci52MS5Mb2dpbkJ5R29vZ2xlUmVxdWVzdBoyLm1ldGFkcmVh",
            "bS5hcHAuaGVyLmF2YXRhci52MS5Mb2dpbkJ5R29vZ2xlUmVzcG9uc2UiJoLT",
            "5JMCICIbL2hlci1hdmF0YXIvbG9naW5fYnlfZ29vZ2xlOgEqEpoBCgxMb2dp",
            "bkJ5QXBwbGUSMC5tZXRhZHJlYW0uYXBwLmhlci5hdmF0YXIudjEuTG9naW5C",
            "eUFwcGxlUmVxdWVzdBoxLm1ldGFkcmVhbS5hcHAuaGVyLmF2YXRhci52MS5M",
            "b2dpbkJ5QXBwbGVSZXNwb25zZSIlgtPkkwIfIhovaGVyLWF2YXRhci9sb2dp",
            "bl9ieV9hcHBsZToBKhKJAQoKVXNlckxvZ291dBIuLm1ldGFkcmVhbS5hcHAu",
            "aGVyLmF2YXRhci52MS5Vc2VyTG9nb3V0UmVxdWVzdBovLm1ldGFkcmVhbS5h",
            "cHAuaGVyLmF2YXRhci52MS5Vc2VyTG9nb3V0UmVzcG9uc2UiGoLT5JMCFCIS",
            "L2hlci1hdmF0YXIvbG9nb3V0EpUBCgtVc2VyRGVzdHJveRIvLm1ldGFkcmVh",
            "bS5hcHAuaGVyLmF2YXRhci52MS5Vc2VyRGVzdHJveVJlcXVlc3QaMC5tZXRh",
            "ZHJlYW0uYXBwLmhlci5hdmF0YXIudjEuVXNlckRlc3Ryb3lSZXNwb25zZSIj",
            "gtPkkwIdIhgvaGVyLWF2YXRhci91c2VyX2Rlc3Ryb3k6ASoSggEKB0dldFVz",
            "ZXISKy5tZXRhZHJlYW0uYXBwLmhlci5hdmF0YXIudjEuR2V0VXNlclJlcXVl",
            "c3QaLC5tZXRhZHJlYW0uYXBwLmhlci5hdmF0YXIudjEuR2V0VXNlclJlc3Bv",
            "bnNlIhyC0+STAhYiFC9oZXItYXZhdGFyL2dldF91c2VyEpEBCgpDcmVhdGVV",
            "c2VyEi4ubWV0YWRyZWFtLmFwcC5oZXIuYXZhdGFyLnYxLkNyZWF0ZVVzZXJS",
            "ZXF1ZXN0Gi8ubWV0YWRyZWFtLmFwcC5oZXIuYXZhdGFyLnYxLkNyZWF0ZVVz",
            "ZXJSZXNwb25zZSIigtPkkwIcIhcvaGVyLWF2YXRhci9jcmVhdGVfdXNlcjoB",
            "KhKRAQoKVXBkYXRlVXNlchIuLm1ldGFkcmVhbS5hcHAuaGVyLmF2YXRhci52",
            "MS5VcGRhdGVVc2VyUmVxdWVzdBovLm1ldGFkcmVhbS5hcHAuaGVyLmF2YXRh",
            "ci52MS5VcGRhdGVVc2VyUmVzcG9uc2UiIoLT5JMCHCIXL2hlci1hdmF0YXIv",
            "dXBkYXRlX3VzZXI6ASoSjQEKCUNyZWF0ZUhlchItLm1ldGFkcmVhbS5hcHAu",
            "aGVyLmF2YXRhci52MS5DcmVhdGVIZXJSZXF1ZXN0Gi4ubWV0YWRyZWFtLmFw",
            "cC5oZXIuYXZhdGFyLnYxLkNyZWF0ZUhlclJlc3BvbnNlIiGC0+STAhsiFi9o",
            "ZXItYXZhdGFyL2NyZWF0ZV9oZXI6ASoSgQEKBkdldEhlchIqLm1ldGFkcmVh",
            "bS5hcHAuaGVyLmF2YXRhci52MS5HZXRIZXJSZXF1ZXN0GisubWV0YWRyZWFt",
            "LmFwcC5oZXIuYXZhdGFyLnYxLkdldEhlclJlc3BvbnNlIh6C0+STAhgiEy9o",
            "ZXItYXZhdGFyL2dldF9oZXI6ASoSjQEKCVVwZGF0ZUhlchItLm1ldGFkcmVh",
            "bS5hcHAuaGVyLmF2YXRhci52MS5VcGRhdGVIZXJSZXF1ZXN0Gi4ubWV0YWRy",
            "ZWFtLmFwcC5oZXIuYXZhdGFyLnYxLlVwZGF0ZUhlclJlc3BvbnNlIiGC0+ST",
            "AhsiFi9oZXItYXZhdGFyL3VwZGF0ZV9oZXI6ASoyjQUKD0hlclZvaWNlU2Vy",
            "dmljZRKoAQoQSGVyVm9pY2VSdGNUb2tlbhI0Lm1ldGFkcmVhbS5hcHAuaGVy",
            "LmF2YXRhci52MS5IZXJWb2ljZVJ0Y1Rva2VuUmVxdWVzdBo1Lm1ldGFkcmVh",
            "bS5hcHAuaGVyLmF2YXRhci52MS5IZXJWb2ljZVJ0Y1Rva2VuUmVzcG9uc2Ui",
            "J4LT5JMCISIfL2hlci1hdmF0YXIvaGVyX3ZvaWNlX3J0Y190b2tlbhKbAQoN",
            "SGVyVm9pY2VTdGFydBIxLm1ldGFkcmVhbS5hcHAuaGVyLmF2YXRhci52MS5I",
            "ZXJWb2ljZVN0YXJ0UmVxdWVzdBoyLm1ldGFkcmVhbS5hcHAuaGVyLmF2YXRh",
            "ci52MS5IZXJWb2ljZVN0YXJ0UmVzcG9uc2UiI4LT5JMCHSIbL2hlci1hdmF0",
            "YXIvaGVyX3ZvaWNlX3N0YXJ0EpcBCgxIZXJWb2ljZVN0b3ASMC5tZXRhZHJl",
            "YW0uYXBwLmhlci5hdmF0YXIudjEuSGVyVm9pY2VTdG9wUmVxdWVzdBoxLm1l",
            "dGFkcmVhbS5hcHAuaGVyLmF2YXRhci52MS5IZXJWb2ljZVN0b3BSZXNwb25z",
            "ZSIigtPkkwIcIhovaGVyLWF2YXRhci9oZXJfdm9pY2Vfc3RvcBKWAQoLSGVy",
            "VGV4dENoYXQSLy5tZXRhZHJlYW0uYXBwLmhlci5hdmF0YXIudjEuSGVyVGV4",
            "dENoYXRSZXF1ZXN0GjAubWV0YWRyZWFtLmFwcC5oZXIuYXZhdGFyLnYxLkhl",
            "clRleHRDaGF0UmVzcG9uc2UiJILT5JMCHiIZL2hlci1hdmF0YXIvaGVyX3Rl",
            "eHRfY2hhdDoBKjLXAwoUSGVyUGVyY2VwdGlvblNlcnZpY2USjQEKCUdlb1Jl",
            "cG9ydBItLm1ldGFkcmVhbS5hcHAuaGVyLmF2YXRhci52MS5HZW9SZXBvcnRS",
            "ZXF1ZXN0Gi4ubWV0YWRyZWFtLmFwcC5oZXIuYXZhdGFyLnYxLkdlb1JlcG9y",
            "dFJlc3BvbnNlIiGC0+STAhsiFi9oZXItYXZhdGFyL2dlby9yZXBvcnQ6ASoS",
            "kQEKCkdlb1JldmVyc2USLi5tZXRhZHJlYW0uYXBwLmhlci5hdmF0YXIudjEu",
            "R2VvUmV2ZXJzZVJlcXVlc3QaLy5tZXRhZHJlYW0uYXBwLmhlci5hdmF0YXIu",
            "djEuR2VvUmV2ZXJzZVJlc3BvbnNlIiKC0+STAhwiFy9oZXItYXZhdGFyL2dl",
            "by9yZXZlcnNlOgEqEpoBCgxHZW9OZWFyYnlQb2kSMC5tZXRhZHJlYW0uYXBw",
            "Lmhlci5hdmF0YXIudjEuR2VvTmVhcmJ5UG9pUmVxdWVzdBoxLm1ldGFkcmVh",
            "bS5hcHAuaGVyLmF2YXRhci52MS5HZW9OZWFyYnlQb2lSZXNwb25zZSIlgtPk",
            "kwIfIhovaGVyLWF2YXRhci9nZW8vbmVhcmJ5X3BvaToBKjLaAQoTSGVyQWdl",
            "bnRUb29sU2VydmljZRLCAQoUU2VhcmNoR29vZ2xlTmV3c1Rvb2wSOC5tZXRh",
            "ZHJlYW0uYXBwLmhlci5hdmF0YXIudjEuU2VhcmNoR29vZ2xlTmV3c1Rvb2xS",
            "ZXF1ZXN0GjkubWV0YWRyZWFtLmFwcC5oZXIuYXZhdGFyLnYxLlNlYXJjaEdv",
            "b2dsZU5ld3NUb29sUmVzcG9uc2UiNYLT5JMCLyIqL2hlci1hdmF0YXIvaW5u",
            "ZXIvdG9vbHMvc2VhcmNoX2dvb2dsZV9uZXdzOgEqQq4BCh9jb20ubWV0YWRy",
            "ZWFtLmFwcC5oZXIuYXZhdGFyLnYxQhVIZXJBdmF0YXJTZXJ2aWNlUHJvdG9Q",
            "AVpKZ2l0bGFiLmJvbmRlZS1pbmMuY29tL2lkbC9idWZidWlsZC9nby9wcm90",
            "by9tZXRhZHJlYW0vYXBwL2hlci9hdmF0YXIvdjE7djGiAgdNQVBIRVIxqgIb",
            "TWV0YWRyZWFtLkFwcC5IZXIuQXZhdGFyLlYxYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Api.AnnotationsReflection.Descriptor, global::Metadream.App.Her.Avatar.V1.AppHerAvatarV1ResourcesReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
