
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace GameConfig
{
public partial class Tables
{
    /// <summary>
    /// Original 121 张卡牌主数据
    /// </summary>
    public stacklands.TbCard TbCard {get; }
    /// <summary>
    /// 村民、友好动物和敌对单位基础属性
    /// </summary>
    public stacklands.TbUnit TbUnit {get; }
    /// <summary>
    /// Original 三张装备定义
    /// </summary>
    public stacklands.TbEquipment TbEquipment {get; }
    /// <summary>
    /// 建筑、资源节点和特殊结构参数
    /// </summary>
    public stacklands.TbStructure TbStructure {get; }
    /// <summary>
    /// 32 张 Original 点子及炉灶料理变体
    /// </summary>
    public stacklands.TbRecipe TbRecipe {get; }
    /// <summary>
    /// 卡包、采集、探索和敌人掉落池
    /// </summary>
    public stacklands.TbLootPool TbLootPool {get; }
    /// <summary>
    /// 掉落池条目；未知概率不填零
    /// </summary>
    public stacklands.TbLootEntry TbLootEntry {get; }
    /// <summary>
    /// 采集、探索、生产、出售和特殊交互入口
    /// </summary>
    public stacklands.TbCardAction TbCardAction {get; }
    /// <summary>
    /// 地下墓穴和旅行商车确定性里程碑
    /// </summary>
    public stacklands.TbMilestone TbMilestone {get; }
    /// <summary>
    /// 主大陆八个购买卡包和两个特殊卡包
    /// </summary>
    public stacklands.TbBoosterPack TbBoosterPack {get; }
    /// <summary>
    /// 每个卡包的独立卡槽
    /// </summary>
    public stacklands.TbBoosterSlot TbBoosterSlot {get; }
    /// <summary>
    /// Original 基础版 56 项任务
    /// </summary>
    public stacklands.TbQuest TbQuest {get; }
    /// <summary>
    /// Original 主大陆全局规则
    /// </summary>
    public stacklands.TbWorldRule TbWorldRule {get; }
    /// <summary>
    /// 卡牌触发式特殊效果与局内限制
    /// </summary>
    public stacklands.TbCardEffect TbCardEffect {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        TbCard = new stacklands.TbCard(loader("stacklands_tbcard"));
        TbUnit = new stacklands.TbUnit(loader("stacklands_tbunit"));
        TbEquipment = new stacklands.TbEquipment(loader("stacklands_tbequipment"));
        TbStructure = new stacklands.TbStructure(loader("stacklands_tbstructure"));
        TbRecipe = new stacklands.TbRecipe(loader("stacklands_tbrecipe"));
        TbLootPool = new stacklands.TbLootPool(loader("stacklands_tblootpool"));
        TbLootEntry = new stacklands.TbLootEntry(loader("stacklands_tblootentry"));
        TbCardAction = new stacklands.TbCardAction(loader("stacklands_tbcardaction"));
        TbMilestone = new stacklands.TbMilestone(loader("stacklands_tbmilestone"));
        TbBoosterPack = new stacklands.TbBoosterPack(loader("stacklands_tbboosterpack"));
        TbBoosterSlot = new stacklands.TbBoosterSlot(loader("stacklands_tbboosterslot"));
        TbQuest = new stacklands.TbQuest(loader("stacklands_tbquest"));
        TbWorldRule = new stacklands.TbWorldRule(loader("stacklands_tbworldrule"));
        TbCardEffect = new stacklands.TbCardEffect(loader("stacklands_tbcardeffect"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbCard.ResolveRef(this);
        TbUnit.ResolveRef(this);
        TbEquipment.ResolveRef(this);
        TbStructure.ResolveRef(this);
        TbRecipe.ResolveRef(this);
        TbLootPool.ResolveRef(this);
        TbLootEntry.ResolveRef(this);
        TbCardAction.ResolveRef(this);
        TbMilestone.ResolveRef(this);
        TbBoosterPack.ResolveRef(this);
        TbBoosterSlot.ResolveRef(this);
        TbQuest.ResolveRef(this);
        TbWorldRule.ResolveRef(this);
        TbCardEffect.ResolveRef(this);
    }
}

}
