
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace GameConfig
{
public partial class Tables
{
    public item.TbItem TbItem {get; }
    /// <summary>
    /// 马戏牌局表演者牌
    /// </summary>
    public carnival.TbPerformer TbPerformer {get; }
    /// <summary>
    /// 马戏牌局消耗牌
    /// </summary>
    public carnival.TbConsumable TbConsumable {get; }
    /// <summary>
    /// 扑克牌强化效果
    /// </summary>
    public carnival.TbCardEnhancement TbCardEnhancement {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        TbItem = new item.TbItem(loader("item_tbitem"));
        TbPerformer = new carnival.TbPerformer(loader("carnival_tbperformer"));
        TbConsumable = new carnival.TbConsumable(loader("carnival_tbconsumable"));
        TbCardEnhancement = new carnival.TbCardEnhancement(loader("carnival_tbcardenhancement"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbItem.ResolveRef(this);
        TbPerformer.ResolveRef(this);
        TbConsumable.ResolveRef(this);
        TbCardEnhancement.ResolveRef(this);
    }
}

}
